import Groups.GeodesicGrowth

open Filter

namespace VirtuallyEngel

/-!
# A virtually Engel group

This file records Bodart's virtually `3`-step nilpotent example with intermediate geodesic
growth.
-/

/-- Generators in the two-generator presentation used for Bodart's virtually Engel group. -/
inductive Generator where
  | a
  | t
  deriving DecidableEq, Fintype

noncomputable instance : Primcodable Generator :=
  Primcodable.ofEquiv (Fin 2) (Fintype.equivFin Generator)

/-- The free-group word corresponding to the generator `a`. -/
abbrev A : FreeGroup Generator :=
  FreeGroup.of Generator.a

/-- The free-group word corresponding to the generator `t`. -/
abbrev T : FreeGroup Generator :=
  FreeGroup.of Generator.t

/-- The conjugate `t⁻¹ a t`, written `aᵗ` in the literature. -/
abbrev Aconj : FreeGroup Generator :=
  T⁻¹ * A * T

/-- Hall's commutator convention is `x⁻¹ * y⁻¹ * x * y`, opposite to mathlib's
`⁅x, y⁆ = x * y * x⁻¹ * y⁻¹`.

This is the middle generator matching the experimentally derived normal forms in the coordinate
model below. -/
abbrev HallX : FreeGroup Generator :=
  A⁻¹ * Aconj⁻¹ * A * Aconj

/-- The corresponding Hall-style third-step commutator. In coordinates this agrees with the
presentation commutator `C`. -/
abbrev HallY : FreeGroup Generator :=
  A⁻¹ * HallX⁻¹ * A * HallX

/-- The common third-step commutator in Bodart's presentation. -/
abbrev C : FreeGroup Generator :=
  ⁅A, ⁅A, Aconj⁆⁆

/-- Relators for Bodart's virtually Engel group:
`t² = 1`, `C = [aᵗ, [a, aᵗ]]`, and `C` commutes with both `a` and `aᵗ`. -/
abbrev relators : Set (FreeGroup Generator) :=
  {T * T, C * (⁅Aconj, ⁅A, Aconj⁆⁆)⁻¹, ⁅C, A⁆, ⁅C, Aconj⁆}

/-- Bodart's virtually Engel group. -/
abbrev Group : Type :=
  PresentedGroup relators

/-- The geodesic-growth alphabet `S = {a, a⁻¹, t}` used in Bodart's theorem. -/
inductive Letter where
  | a
  | aInv
  | t
  deriving DecidableEq, Fintype

/-- Interpretation of the Bodart alphabet in the presented group. -/
def letterValue : Letter → Group
  | .a => PresentedGroup.mk relators A
  | .aInv => (PresentedGroup.mk relators A)⁻¹
  | .t => PresentedGroup.mk relators T

/-- Geodesic growth with respect to `S = {a, a⁻¹, t}`. -/
noncomputable abbrev geodesicGrowth : ℕ → ℕ :=
  PresentedGroup.geodesicGrowth relators letterValue

/-- The comparison function appearing in Bodart's asymptotic estimate. -/
noncomputable def modelGrowth (n : ℕ) : ℝ :=
  Real.exp ((n : ℝ).rpow ((3 : ℝ) / 5) * Real.log (n : ℝ))

/-- A literal formalization of `γ(n) ≍ exp(n^{3/5} log n)` as an eventual two-sided bound. -/
def theorem_4_statement : Prop :=
  ∃ c₁ c₂ : ℝ,
    0 < c₁ ∧
    c₁ ≤ c₂ ∧
    ∀ᶠ n : ℕ in atTop,
      c₁ * modelGrowth n ≤ (geodesicGrowth n : ℝ) ∧
      (geodesicGrowth n : ℝ) ≤ c₂ * modelGrowth n

/-!
## A computable coordinate model

The next step toward an internal proof of the Bodart witness facts is to work with an explicit
computable model of the underlying virtually Engel group. The model below packages the Engel
subgroup by integer coordinates coming from Bodart's path invariants, together with an order-two
symmetry acting by reflection.
-/

/-- Integer coordinates for the Engel subgroup generated by the two diagonal steps
`a = (1, 0, 0, 0)` and `b = (0, 1, 0, 0)`.

The fields are the two diagonal coordinates together with the algebraic area and three times the
`y`-barycenter used in Bodart's path model. -/
structure EngelCoords where
  u : ℤ
  v : ℤ
  area : ℤ
  bary3 : ℤ
  deriving DecidableEq

noncomputable instance : Primcodable EngelCoords :=
  Primcodable.ofEquiv (ℤ × ℤ × ℤ × ℤ)
    { toFun := fun g => (g.u, g.v, g.area, g.bary3)
      invFun := fun p => ⟨p.1, p.2.1, p.2.2.1, p.2.2.2⟩
      left_inv := by
        intro g
        cases g
        rfl
      right_inv := by
        intro p
        cases p
        rfl }

/-- Half of the determinant term appearing in Bodart's concatenation formula, expressed in the
diagonal coordinates. -/
def EngelCoords.det2 (g h : EngelCoords) : ℤ :=
  g.v * h.u - g.u * h.v

instance : Mul EngelCoords where
  mul g h :=
    { u := g.u + h.u
      v := g.v + h.v
      area := g.area + h.area + EngelCoords.det2 g h
      bary3 := g.bary3 + h.bary3 + 3 * (g.u - g.v) * h.area +
        (2 * (g.u - g.v) + (h.u - h.v)) * EngelCoords.det2 g h }

instance : One EngelCoords where
  one := ⟨0, 0, 0, 0⟩

instance : Inv EngelCoords where
  inv g := ⟨-g.u, -g.v, -g.area, -g.bary3 + 3 * (g.u - g.v) * g.area⟩

@[simp] theorem EngelCoords.mul_u (g h : EngelCoords) : (g * h).u = g.u + h.u := rfl
@[simp] theorem EngelCoords.mul_v (g h : EngelCoords) : (g * h).v = g.v + h.v := rfl
@[simp] theorem EngelCoords.mul_area (g h : EngelCoords) :
    (g * h).area = g.area + h.area + EngelCoords.det2 g h := rfl
@[simp] theorem EngelCoords.mul_bary3 (g h : EngelCoords) :
    (g * h).bary3 = g.bary3 + h.bary3 + 3 * (g.u - g.v) * h.area +
      (2 * (g.u - g.v) + (h.u - h.v)) * EngelCoords.det2 g h := rfl
@[simp] theorem EngelCoords.one_u : (1 : EngelCoords).u = 0 := rfl
@[simp] theorem EngelCoords.one_v : (1 : EngelCoords).v = 0 := rfl
@[simp] theorem EngelCoords.one_area : (1 : EngelCoords).area = 0 := rfl
@[simp] theorem EngelCoords.one_bary3 : (1 : EngelCoords).bary3 = 0 := rfl
@[simp] theorem EngelCoords.inv_u (g : EngelCoords) : g⁻¹.u = -g.u := rfl
@[simp] theorem EngelCoords.inv_v (g : EngelCoords) : g⁻¹.v = -g.v := rfl
@[simp] theorem EngelCoords.inv_area (g : EngelCoords) : g⁻¹.area = -g.area := rfl
@[simp] theorem EngelCoords.inv_bary3 (g : EngelCoords) :
    g⁻¹.bary3 = -g.bary3 + 3 * (g.u - g.v) * g.area := rfl

@[ext]
theorem EngelCoords.ext
    {g h : EngelCoords}
    (hu : g.u = h.u) (hv : g.v = h.v) (harea : g.area = h.area)
    (hbary3 : g.bary3 = h.bary3) : g = h := by
  cases g
  cases h
  simp_all

instance : _root_.Group EngelCoords where
  mul_assoc g h k := by
    ext <;> simp [EngelCoords.det2] <;> ring
  one_mul g := by
    ext <;> simp [EngelCoords.det2]
  mul_one g := by
    ext <;> simp [EngelCoords.det2]
  inv_mul_cancel g := by
    ext <;> simp [EngelCoords.det2] <;> ring

/-- The coordinate image of the diagonal step `a`. -/
abbrev engelA : EngelCoords :=
  ⟨1, 0, 0, 0⟩

/-- The coordinate image of `aᵗ = t⁻¹ a t`. -/
abbrev engelAconj : EngelCoords :=
  ⟨0, -1, 0, 0⟩

/-- The corrected Hall-style commutator generator. -/
abbrev engelHallX : EngelCoords :=
  ⟨0, 0, 2, -6⟩

/-- The central Hall-style commutator generator. -/
abbrev engelHallY : EngelCoords :=
  ⟨0, 0, 0, 6⟩

@[simp] theorem engelA_pow (n : ℕ) : engelA ^ n = ⟨n, 0, 0, 0⟩ := by
  induction n with
  | zero => rfl
  | succ n ih =>
      ext <;> simp [engelA, pow_succ, ih, EngelCoords.det2] <;> ring

@[simp] theorem engelAconj_pow (n : ℕ) : engelAconj ^ n = ⟨0, -(n : ℤ), 0, 0⟩ := by
  induction n with
  | zero => rfl
  | succ n ih =>
      ext <;> simp [engelAconj, pow_succ, ih, EngelCoords.det2] <;> ring

@[simp] theorem engelHallX_pow (n : ℕ) :
    engelHallX ^ n = ⟨0, 0, 2 * (n : ℤ), -6 * (n : ℤ)⟩ := by
  induction n with
  | zero => rfl
  | succ n ih =>
      ext <;> simp [engelHallX, pow_succ, ih, EngelCoords.det2] <;> ring

@[simp] theorem engelHallY_pow (n : ℕ) :
    engelHallY ^ n = ⟨0, 0, 0, 6 * (n : ℤ)⟩ := by
  induction n with
  | zero => rfl
  | succ n ih =>
      ext <;> simp [engelHallY, pow_succ, ih, EngelCoords.det2] <;> ring

@[simp] theorem engelA_zpow (n : ℤ) : engelA ^ n = ⟨n, 0, 0, 0⟩ := by
  cases n with
  | ofNat n =>
      simpa [zpow_natCast] using engelA_pow n
  | negSucc n =>
      change engelA ^ Int.negSucc n = ⟨Int.negSucc n, 0, 0, 0⟩
      rw [zpow_negSucc, engelA_pow]
      ext <;> simp [Int.negSucc_eq]

@[simp] theorem engelAconj_zpow (n : ℤ) : engelAconj ^ n = ⟨0, -n, 0, 0⟩ := by
  cases n with
  | ofNat n =>
      simpa [zpow_natCast] using engelAconj_pow n
  | negSucc n =>
      change engelAconj ^ Int.negSucc n = ⟨0, -(Int.negSucc n), 0, 0⟩
      rw [zpow_negSucc, engelAconj_pow]
      ext <;> simp [Int.negSucc_eq]

@[simp] theorem engelHallX_zpow (n : ℤ) :
    engelHallX ^ n = ⟨0, 0, 2 * n, -6 * n⟩ := by
  cases n with
  | ofNat n =>
      simpa [zpow_natCast] using engelHallX_pow n
  | negSucc n =>
      change engelHallX ^ Int.negSucc n = ⟨0, 0, 2 * Int.negSucc n, -6 * Int.negSucc n⟩
      rw [zpow_negSucc, engelHallX_pow]
      ext <;> simp [Int.negSucc_eq] <;> ring

@[simp] theorem engelHallY_zpow (n : ℤ) :
    engelHallY ^ n = ⟨0, 0, 0, 6 * n⟩ := by
  cases n with
  | ofNat n =>
      simpa [zpow_natCast] using engelHallY_pow n
  | negSucc n =>
      change engelHallY ^ Int.negSucc n = ⟨0, 0, 0, 6 * Int.negSucc n⟩
      rw [zpow_negSucc, engelHallY_pow]
      ext <;> simp [Int.negSucc_eq] <;> ring

/-- The order-two symmetry induced by reflection across the `y`-axis in Bodart's path model. -/
def EngelCoords.reflect (g : EngelCoords) : EngelCoords :=
  ⟨-g.v, -g.u, -g.area, -g.bary3⟩

@[simp] theorem EngelCoords.reflect_reflect (g : EngelCoords) :
    g.reflect.reflect = g := by
  ext <;> simp [EngelCoords.reflect]

@[simp] theorem EngelCoords.reflect_mul (g h : EngelCoords) :
    (g * h).reflect = g.reflect * h.reflect := by
  ext <;> simp [EngelCoords.reflect, EngelCoords.det2] <;> ring

/-- Reflection as a multiplicative automorphism of the Engel-coordinate group. -/
def EngelCoords.reflectAut : MulAut EngelCoords where
  toFun := EngelCoords.reflect
  invFun := EngelCoords.reflect
  left_inv := EngelCoords.reflect_reflect
  right_inv := EngelCoords.reflect_reflect
  map_mul' := EngelCoords.reflect_mul

/-- The order-two symmetry adjoining the Engel subgroup. -/
inductive Symmetry where
  | id
  | flip
  deriving DecidableEq, Fintype

instance : One Symmetry where
  one := .id

instance : Mul Symmetry where
  mul
    | .id, x => x
    | .flip, .id => .flip
    | .flip, .flip => .id

instance : Inv Symmetry where
  inv := id

@[simp] theorem Symmetry.inv_id : (Symmetry.id)⁻¹ = Symmetry.id := rfl
@[simp] theorem Symmetry.inv_flip : (Symmetry.flip)⁻¹ = Symmetry.flip := rfl

instance : _root_.Group Symmetry where
  mul_assoc a b c := by
    cases a <;> cases b <;> cases c <;> rfl
  one_mul a := by
    cases a <;> rfl
  mul_one a := by
    cases a <;> rfl
  inv_mul_cancel a := by
    cases a <;> rfl

noncomputable instance : Primcodable Symmetry :=
  Primcodable.ofEquiv (Fin 2) (Fintype.equivFin Symmetry)

/-- The reflection action of the order-two symmetry on Engel coordinates. -/
def symmetryAction : Symmetry →* MulAut EngelCoords where
  toFun
    | .id => 1
    | .flip => EngelCoords.reflectAut
  map_one' := rfl
  map_mul' := by
    intro a b
    cases a <;> cases b
    · rfl
    · rfl
    · rfl
    · exact DFunLike.ext _ _ fun g => by
        simp [MulAut.mul_apply, EngelCoords.reflectAut, EngelCoords.reflect]

/-- A computable semidirect-product model for Bodart's virtually Engel group. -/
abbrev CoordGroup :=
  EngelCoords ⋊[symmetryAction] Symmetry

/-- The diagonal generator `a` inside the coordinate model. -/
abbrev coordA : CoordGroup :=
  SemidirectProduct.inl engelA

/-- The diagonal generator `b` inside the Engel subgroup. -/
abbrev coordB : CoordGroup :=
  SemidirectProduct.inl ⟨0, 1, 0, 0⟩

/-- The coordinate image of `aᵗ`. -/
abbrev coordAconj : CoordGroup :=
  SemidirectProduct.inl engelAconj

/-- The corrected Hall-style middle commutator. -/
abbrev coordHallX : CoordGroup :=
  SemidirectProduct.inl engelHallX

/-- The central Hall-style commutator. -/
abbrev coordHallY : CoordGroup :=
  SemidirectProduct.inl engelHallY

/-- The order-two symmetry `t` inside the coordinate model. -/
abbrev coordT : CoordGroup :=
  SemidirectProduct.inr Symmetry.flip

/-- The presentation generators interpreted in the computable coordinate model. -/
def coordGenerator : Generator → CoordGroup
  | .a => coordA
  | .t => coordT

@[simp] theorem coordA_zpow (n : ℤ) : coordA ^ n = SemidirectProduct.inl ⟨n, 0, 0, 0⟩ := by
  simpa [coordA] using
    (((SemidirectProduct.inl : EngelCoords →* CoordGroup).map_zpow engelA n).symm)

@[simp] theorem coordAconj_zpow (n : ℤ) :
    coordAconj ^ n = SemidirectProduct.inl ⟨0, -n, 0, 0⟩ := by
  simpa [coordAconj] using
    (((SemidirectProduct.inl : EngelCoords →* CoordGroup).map_zpow engelAconj n).symm)

@[simp] theorem coordHallX_zpow (n : ℤ) :
    coordHallX ^ n = SemidirectProduct.inl ⟨0, 0, 2 * n, -6 * n⟩ := by
  simpa [coordHallX] using
    (((SemidirectProduct.inl : EngelCoords →* CoordGroup).map_zpow engelHallX n).symm)

@[simp] theorem coordHallY_zpow (n : ℤ) :
    coordHallY ^ n = SemidirectProduct.inl ⟨0, 0, 0, 6 * n⟩ := by
  simpa [coordHallY] using
    (((SemidirectProduct.inl : EngelCoords →* CoordGroup).map_zpow engelHallY n).symm)

@[simp] theorem coordT_sq : coordT * coordT = 1 := by
  native_decide

@[simp] theorem coord_conj_a :
    coordT⁻¹ * coordA * coordT = coordB⁻¹ := by
  native_decide

@[simp] theorem coord_aconj :
    FreeGroup.lift coordGenerator Aconj = coordAconj := by
  native_decide

/-- This records the commutator-convention mismatch: mathlib's `⁅A, Aconj⁆` is not the Hall
generator used by the experimentally derived normal forms. -/
@[simp] theorem coord_mathlib_commutator :
    FreeGroup.lift coordGenerator ⁅A, Aconj⁆ = SemidirectProduct.inl ⟨0, 0, 2, 6⟩ := by
  native_decide

@[simp] theorem coord_hallX :
    FreeGroup.lift coordGenerator HallX = coordHallX := by
  native_decide

@[simp] theorem coord_hallY :
    FreeGroup.lift coordGenerator HallY = coordHallY := by
  native_decide

@[simp] theorem coord_C :
    FreeGroup.lift coordGenerator C = coordHallY := by
  native_decide

@[simp] theorem coord_relator_t2 :
    FreeGroup.lift coordGenerator (T * T) = 1 := by
  native_decide

@[simp] theorem coord_relator_commutator :
    FreeGroup.lift coordGenerator (C * (⁅Aconj, ⁅A, Aconj⁆⁆)⁻¹) = 1 := by
  native_decide

@[simp] theorem coord_relator_central_a :
    FreeGroup.lift coordGenerator ⁅C, A⁆ = 1 := by
  native_decide

@[simp] theorem coord_relator_central_aconj :
    FreeGroup.lift coordGenerator ⁅C, Aconj⁆ = 1 := by
  native_decide

/-- The presentation maps into the computable coordinate model. This is the concrete target for
the eventual internal proof of the word-problem witness. -/
def toCoordGroup : PresentedGroup relators →* CoordGroup :=
  PresentedGroup.toGroup (f := coordGenerator) <| by
    intro r hr
    simp only [relators, Set.mem_insert_iff, Set.mem_singleton_iff] at hr
    rcases hr with rfl | rfl | rfl | rfl
    · exact coord_relator_t2
    · exact coord_relator_commutator
    · exact coord_relator_central_a
    · exact coord_relator_central_aconj

/-!
## The lattice cut out by the generators

The explicit coordinate model above is larger than the subgroup generated by the two diagonal
steps. The latter is cut out by two congruence conditions, corresponding to the area and
barycentric coordinates in Bodart's path model.
-/

/-- The parity residue governing the area coordinate of the Engel lattice. -/
def EngelCoords.areaResidue (g : EngelCoords) : ℤ :=
  g.area + g.u * g.v

/-- The congruence residue governing the barycentric coordinate of the Engel lattice. -/
def EngelCoords.baryResidue (g : EngelCoords) : ℤ :=
  g.bary3 - 3 * g.area * (g.u - g.v) - g.u * g.u * g.v + 2 * g.u * g.v * g.v

/-- The lattice subgroup generated by the two diagonal steps inside the coordinate model. -/
def EngelCoords.InLattice (g : EngelCoords) : Prop :=
  2 ∣ g.areaResidue ∧ 6 ∣ g.baryResidue

@[simp] theorem EngelCoords.areaResidue_one : (1 : EngelCoords).areaResidue = 0 := by
  simp [EngelCoords.areaResidue]

@[simp] theorem EngelCoords.baryResidue_one : (1 : EngelCoords).baryResidue = 0 := by
  simp [EngelCoords.baryResidue]

@[simp] theorem EngelCoords.areaResidue_mul (g h : EngelCoords) :
    (g * h).areaResidue = g.areaResidue + h.areaResidue + 2 * g.v * h.u := by
  simp [EngelCoords.areaResidue, EngelCoords.det2]
  ring

@[simp] theorem EngelCoords.baryResidue_mul (g h : EngelCoords) :
    (g * h).baryResidue =
      g.baryResidue + h.baryResidue
        - 3 * ((g.areaResidue) * (h.u - h.v) + h.u * g.v * (h.u - g.v - 2 * h.v)) := by
  simp [EngelCoords.baryResidue, EngelCoords.areaResidue, EngelCoords.det2]
  ring

@[simp] theorem EngelCoords.areaResidue_inv (g : EngelCoords) :
    g⁻¹.areaResidue = -g.areaResidue + 2 * g.u * g.v := by
  simp [EngelCoords.areaResidue]
  ring

@[simp] theorem EngelCoords.baryResidue_inv (g : EngelCoords) :
    g⁻¹.baryResidue = -g.baryResidue - 3 * g.area * (g.u - g.v) := by
  simp [EngelCoords.baryResidue]
  ring

@[simp] theorem EngelCoords.areaResidue_reflect (g : EngelCoords) :
    g.reflect.areaResidue = -g.areaResidue + 2 * g.u * g.v := by
  simp [EngelCoords.reflect, EngelCoords.areaResidue]
  ring

@[simp] theorem EngelCoords.baryResidue_reflect (g : EngelCoords) :
    g.reflect.baryResidue = -g.baryResidue - 3 * g.u * g.v * (g.u - g.v) := by
  simp [EngelCoords.reflect, EngelCoords.baryResidue]
  ring

@[simp] theorem EngelCoords.inLattice_one : EngelCoords.InLattice 1 := by
  simp [EngelCoords.InLattice]

theorem EngelCoords.inLattice_mul {g h : EngelCoords}
    (hg : EngelCoords.InLattice g) (hh : EngelCoords.InLattice h) :
    EngelCoords.InLattice (g * h) := by
  rcases hg with ⟨hgArea, hgBary⟩
  rcases hh with ⟨hhArea, hhBary⟩
  constructor
  · rcases hgArea with ⟨kg, hkg⟩
    rcases hhArea with ⟨kh, hkh⟩
    have hmul := EngelCoords.areaResidue_mul g h
    refine ⟨kg + kh + g.v * h.u, ?_⟩
    rw [hmul, hkg, hkh]
    ring
  · rcases hgBary with ⟨lg, hlg⟩
    rcases hhBary with ⟨lh, hlh⟩
    have hEvenCorr : 2 ∣ g.areaResidue * (h.u - h.v) + h.u * g.v * (h.u - g.v - 2 * h.v) := by
      have h₁ : 2 ∣ g.areaResidue * (h.u - h.v) := by
        rcases hgArea with ⟨kg, hkg⟩
        refine ⟨kg * (h.u - h.v), ?_⟩
        rw [hkg]
        ring
      have h₂even : Even (h.u * g.v * (h.u - g.v - 2 * h.v)) := by
        by_cases hu : Even h.u
        · exact Int.even_mul.mpr <| Or.inl <| Int.even_mul.mpr <| Or.inl hu
        · by_cases hv : Even g.v
          · exact Int.even_mul.mpr <| Or.inl <| Int.even_mul.mpr <| Or.inr hv
          · have hsub : Even (h.u - g.v) := by
              rw [Int.even_sub]
              simp [hu, hv]
            have htwov : Even (2 * h.v) := by
              exact Int.even_mul.mpr <| Or.inl (by decide : Even (2 : ℤ))
            have hparen : Even (h.u - g.v - 2 * h.v) := by
              rw [Int.even_sub]
              simp [hsub, htwov]
            exact Int.even_mul.mpr <| Or.inr hparen
      exact dvd_add h₁ (even_iff_two_dvd.mp h₂even)
    rcases hEvenCorr with ⟨kc, hkc⟩
    have hmul := EngelCoords.baryResidue_mul g h
    refine ⟨lg + lh - kc, ?_⟩
    rw [hmul, hlg, hlh, hkc]
    ring

theorem EngelCoords.inLattice_inv {g : EngelCoords} (hg : EngelCoords.InLattice g) :
    EngelCoords.InLattice g⁻¹ := by
  rcases hg with ⟨hgArea, hgBary⟩
  constructor
  · rcases hgArea with ⟨kg, hkg⟩
    have hinv := EngelCoords.areaResidue_inv g
    refine ⟨-kg + g.u * g.v, ?_⟩
    rw [hinv, hkg]
    ring
  · rcases hgBary with ⟨lg, hlg⟩
    have hEven : 2 ∣ g.area * (g.u - g.v) := by
      rcases hgArea with ⟨kg, hkg⟩
      have hsum : 2 ∣ (g.area + g.u * g.v) * (g.u - g.v) := by
        have hkg' : g.area + g.u * g.v = 2 * kg := by
          simpa [EngelCoords.areaResidue] using hkg
        refine ⟨kg * (g.u - g.v), ?_⟩
        rw [hkg']
        ring
      have huvEven : Even (g.u * g.v * (g.u - g.v)) := by
        by_cases hu : Even g.u
        · exact Int.even_mul.mpr <| Or.inl <| Int.even_mul.mpr <| Or.inl hu
        · by_cases hv : Even g.v
          · exact Int.even_mul.mpr <| Or.inl <| Int.even_mul.mpr <| Or.inr hv
          · have hsub : Even (g.u - g.v) := by
              rw [Int.even_sub]
              simp [hu, hv]
            exact Int.even_mul.mpr <| Or.inr hsub
      have huv : 2 ∣ g.u * g.v * (g.u - g.v) := even_iff_two_dvd.mp huvEven
      have hrepr :
          g.area * (g.u - g.v) =
            (g.area + g.u * g.v) * (g.u - g.v) - g.u * g.v * (g.u - g.v) := by
        ring
      rw [hrepr]
      exact dvd_sub hsum huv
    rcases hEven with ⟨kc, hkc⟩
    have hinv := EngelCoords.baryResidue_inv g
    refine ⟨-lg - kc, ?_⟩
    nlinarith [hinv, hlg, hkc]

theorem EngelCoords.inLattice_reflect {g : EngelCoords} (hg : EngelCoords.InLattice g) :
    EngelCoords.InLattice g.reflect := by
  rcases hg with ⟨hgArea, hgBary⟩
  constructor
  · rcases hgArea with ⟨kg, hkg⟩
    have hreflect := EngelCoords.areaResidue_reflect g
    refine ⟨-kg + g.u * g.v, ?_⟩
    rw [hreflect, hkg]
    ring
  · rcases hgBary with ⟨lg, hlg⟩
    have hEven : 2 ∣ g.u * g.v * (g.u - g.v) := by
      have hEvenProd : Even (g.u * g.v * (g.u - g.v)) := by
        by_cases hu : Even g.u
        · exact Int.even_mul.mpr <| Or.inl <| Int.even_mul.mpr <| Or.inl hu
        · by_cases hv : Even g.v
          · exact Int.even_mul.mpr <| Or.inl <| Int.even_mul.mpr <| Or.inr hv
          · have hsub : Even (g.u - g.v) := by
              rw [Int.even_sub]
              simp [hu, hv]
            exact Int.even_mul.mpr <| Or.inr hsub
      exact even_iff_two_dvd.mp hEvenProd
    rcases hEven with ⟨kc, hkc⟩
    have hreflect := EngelCoords.baryResidue_reflect g
    refine ⟨-lg - kc, ?_⟩
    nlinarith [hreflect, hlg, hkc]

theorem EngelCoords.inLattice_action {g : EngelCoords} (s : Symmetry)
    (hg : EngelCoords.InLattice g) :
    EngelCoords.InLattice (symmetryAction s g) := by
  cases s
  · simpa [symmetryAction] using hg
  · simpa [symmetryAction, EngelCoords.reflectAut] using EngelCoords.inLattice_reflect hg

/-- The actual coordinate subgroup in which the presented group lands. -/
def coordLattice : Subgroup CoordGroup where
  carrier := {g | EngelCoords.InLattice g.left}
  one_mem' := EngelCoords.inLattice_one
  mul_mem' {g h} hg hh := by
    have hh' : EngelCoords.InLattice (symmetryAction g.right h.left) :=
      EngelCoords.inLattice_action g.right hh
    simpa [SemidirectProduct.mul_left] using EngelCoords.inLattice_mul hg hh'
  inv_mem' {g} hg := by
    have hInv : EngelCoords.InLattice g.left⁻¹ := EngelCoords.inLattice_inv hg
    have hAct : EngelCoords.InLattice (symmetryAction g.right⁻¹ g.left⁻¹) :=
      EngelCoords.inLattice_action g.right⁻¹ hInv
    simpa [SemidirectProduct.inv_left] using hAct

@[simp] theorem coordA_mem_lattice : coordA ∈ coordLattice := by
  show EngelCoords.InLattice ({ u := 1, v := 0, area := 0, bary3 := 0 } : EngelCoords)
  simp [EngelCoords.InLattice, EngelCoords.areaResidue, EngelCoords.baryResidue]

@[simp] theorem coordT_mem_lattice : coordT ∈ coordLattice := by
  show EngelCoords.InLattice (1 : EngelCoords)
  simp [EngelCoords.InLattice, EngelCoords.areaResidue, EngelCoords.baryResidue]

/-- The presentation generators interpreted in the lattice subgroup of the coordinate model. -/
def coordLatticeGenerator : Generator → coordLattice
  | .a => ⟨coordA, coordA_mem_lattice⟩
  | .t => ⟨coordT, coordT_mem_lattice⟩

/-!
## Corrected Hall-style normal forms

With mathlib's commutator convention, the literal word `⁅A, Aconj⁆` lands at coordinate
`(0, 0, 2, 6)`. The experimentally derived normal forms instead use the Hall-style commutator
`HallX = A⁻¹ * Aconj⁻¹ * A * Aconj`, whose coordinate is `(0, 0, 2, -6)`. The theorems below
package the resulting normal-form formulas and provide a computable spelling of every element in
the coordinate lattice.
-/

/-- Hall-style normal-form word on the Engel subgroup. The exponent on `Aconj` is the literal
free-group exponent, so the second lattice coordinate is `-v`. -/
def hallNormalWord (u v m n : ℤ) : FreeGroup Generator :=
  A ^ u * Aconj ^ v * HallX ^ m * HallY ^ n

theorem coord_hallNormalWord (u v m n : ℤ) :
    FreeGroup.lift coordGenerator (hallNormalWord u v m n) =
      SemidirectProduct.inl
        ⟨u, -v, u * v + 2 * m,
          u * v * (2 * u + v) + 6 * m * (u + v - 1) + 6 * n⟩ := by
  refine SemidirectProduct.ext ?_ ?_
  · apply EngelCoords.ext <;> simp [hallNormalWord, coordGenerator, EngelCoords.det2] <;> ring
  · simp [hallNormalWord, coordGenerator]

/-- In the corrected Hall normal form, the two lattice congruence invariants are exactly the
exponents of the Hall commutators, up to the simple linear shift `n ↦ n - m`. -/
theorem hallNormalWord_areaResidue (u v m n : ℤ) :
    (FreeGroup.lift coordGenerator (hallNormalWord u v m n)).left.areaResidue = 2 * m := by
  simpa [coord_hallNormalWord, EngelCoords.areaResidue]

theorem hallNormalWord_baryResidue (u v m n : ℤ) :
    (FreeGroup.lift coordGenerator (hallNormalWord u v m n)).left.baryResidue = 6 * (n - m) := by
  simp [coord_hallNormalWord, EngelCoords.baryResidue]
  ring

/-- The Hall exponent recovered from the area congruence. -/
def EngelCoords.hallM (g : EngelCoords) : ℤ :=
  g.areaResidue / 2

/-- The Hall exponent recovered from the barycentric congruence. -/
def EngelCoords.hallN (g : EngelCoords) : ℤ :=
  g.hallM + g.baryResidue / 6

/-- The corrected Hall normal-form word attached to a lattice point. -/
def EngelCoords.hallWord (g : EngelCoords) : FreeGroup Generator :=
  hallNormalWord g.u (-g.v) g.hallM g.hallN

theorem EngelCoords.area_eq_hallM {g : EngelCoords} (hg : EngelCoords.InLattice g) :
    g.area = -g.u * g.v + 2 * g.hallM := by
  have hdiv : g.areaResidue / 2 * 2 = g.areaResidue := Int.ediv_mul_cancel hg.1
  calc
    g.area = g.areaResidue - g.u * g.v := by simpa [EngelCoords.areaResidue]
    _ = g.areaResidue / 2 * 2 - g.u * g.v := by rw [hdiv]
    _ = -g.u * g.v + 2 * g.hallM := by
      simp [EngelCoords.hallM]
      ring

theorem EngelCoords.bary3_eq_hallM_hallN {g : EngelCoords} (hg : EngelCoords.InLattice g) :
    g.bary3 =
      -g.u * g.v * (2 * g.u - g.v) + 6 * g.hallM * (g.u - g.v - 1) + 6 * g.hallN := by
  have hdiv : g.baryResidue / 6 * 6 = g.baryResidue := Int.ediv_mul_cancel hg.2
  rw [EngelCoords.hallN]
  calc
    g.bary3 =
      g.baryResidue + 3 * g.area * (g.u - g.v) + g.u * g.u * g.v - 2 * g.u * g.v * g.v := by
        simp [EngelCoords.baryResidue]
        ring
    _ =
      g.baryResidue / 6 * 6 + 3 * (-g.u * g.v + 2 * g.hallM) * (g.u - g.v) +
        g.u * g.u * g.v - 2 * g.u * g.v * g.v := by
          rw [hdiv, EngelCoords.area_eq_hallM hg]
    _ =
      -g.u * g.v * (2 * g.u - g.v) + 6 * g.hallM * (g.u - g.v - 1) +
        6 * (g.hallM + g.baryResidue / 6) := by
          ring

theorem EngelCoords.hallWord_spec {g : EngelCoords} (hg : EngelCoords.InLattice g) :
    FreeGroup.lift coordGenerator g.hallWord = SemidirectProduct.inl g := by
  rw [EngelCoords.hallWord, coord_hallNormalWord]
  refine SemidirectProduct.ext ?_ ?_
  · apply EngelCoords.ext <;>
      simp [EngelCoords.area_eq_hallM hg, EngelCoords.bary3_eq_hallM_hallN hg] <;> ring
  · rfl

/-- A word spelling the order-two symmetry. -/
def symmetryWord : Symmetry → FreeGroup Generator
  | .id => 1
  | .flip => T

@[simp] theorem coord_symmetryWord (s : Symmetry) :
    FreeGroup.lift coordGenerator (symmetryWord s) = SemidirectProduct.inr s := by
  cases s <;> rfl

/-- A computable spelling of an element of the coordinate lattice by the corrected Hall normal
form together with the final symmetry letter. -/
def coordLatticeWord (g : coordLattice) : FreeGroup Generator :=
  g.1.left.hallWord * symmetryWord g.1.right

theorem coordLatticeWord_spec (g : coordLattice) :
    FreeGroup.lift coordGenerator (coordLatticeWord g) = g.1 := by
  rw [coordLatticeWord, map_mul, EngelCoords.hallWord_spec g.2, coord_symmetryWord]
  simpa using (SemidirectProduct.mk_eq_inl_mul_inr g.1.right g.1.left).symm

/-!
## Hall commutation identities inside `PresentedGroup relators`

These identities are the algebraic input to the multiplication-compatibility identity that
discharges `toCoordGroup_injective`. They are stated at the level of `PresentedGroup relators` and
established either by pure free-group algebra (definition of `HallX`, `HallY`, `Aconj`) or by
using one of the four defining relators.
-/

/-- `mk (T * T) = 1` — this is the first defining relator. -/
@[simp] theorem mk_T_sq :
    (PresentedGroup.mk relators (T * T) : PresentedGroup relators) = 1 := by
  exact PresentedGroup.one_of_mem (by simp [relators])

/-- Consequence: `mk T` is its own inverse in the presented group. -/
theorem mk_T_inv :
    (PresentedGroup.mk relators T)⁻¹ =
      (PresentedGroup.mk relators T : PresentedGroup relators) := by
  have h : PresentedGroup.mk relators T * PresentedGroup.mk relators T = 1 := by
    have := mk_T_sq
    simpa [map_mul] using this
  exact inv_eq_of_mul_eq_one_left h

/-- Consequence: `mk T⁻¹ = mk T`. -/
@[simp] theorem mk_T_inv_eq_mk_T :
    (PresentedGroup.mk relators T⁻¹ : PresentedGroup relators) = PresentedGroup.mk relators T := by
  rw [map_inv, mk_T_inv]

/-- Conjugation relation: in the presented group, `T A T = Aconj`. This is essentially the
definition of `Aconj`, made available through `T² = 1`. -/
theorem mk_T_A_T :
    (PresentedGroup.mk relators (T * A * T) : PresentedGroup relators) =
      PresentedGroup.mk relators Aconj := by
  show PresentedGroup.mk relators (T * A * T) = PresentedGroup.mk relators (T⁻¹ * A * T)
  simp [map_mul, mk_T_inv_eq_mk_T]

/-- Commutation of `T` and `A`: `T * A = Aconj * T`. -/
theorem mk_T_A :
    (PresentedGroup.mk relators (T * A) : PresentedGroup relators) =
      PresentedGroup.mk relators (Aconj * T) := by
  -- `Aconj * T = T⁻¹ * A * T * T = T * A * (T * T) = T * A`.
  show PresentedGroup.mk relators (T * A) = PresentedGroup.mk relators (T⁻¹ * A * T * T)
  simp [map_mul, mk_T_inv_eq_mk_T, mul_assoc,
    show (PresentedGroup.mk relators T) * PresentedGroup.mk relators T = 1 by
      have := mk_T_sq; simpa [map_mul] using this]

/-- Commutation of `T` and `Aconj`: `T * Aconj = A * T`. -/
theorem mk_T_Aconj :
    (PresentedGroup.mk relators (T * Aconj) : PresentedGroup relators) =
      PresentedGroup.mk relators (A * T) := by
  -- `T * Aconj = T * (T⁻¹ * A * T) = (T * T⁻¹) * A * T = A * T`.
  show PresentedGroup.mk relators (T * (T⁻¹ * A * T)) = PresentedGroup.mk relators (A * T)
  simp [map_mul, mk_T_inv_eq_mk_T, ← mul_assoc,
    show (PresentedGroup.mk relators T) * PresentedGroup.mk relators T = 1 by
      have := mk_T_sq; simpa [map_mul] using this]

/-- The definition of `HallX = A⁻¹ * Aconj⁻¹ * A * Aconj` in the free group already tells us
that `Aconj * A = A * Aconj * HallX⁻¹` there, and hence in every quotient. -/
theorem mk_Aconj_A :
    (PresentedGroup.mk relators (Aconj * A) : PresentedGroup relators) =
      PresentedGroup.mk relators (A * Aconj * HallX⁻¹) := by
  have h : (Aconj * A : FreeGroup Generator) = A * Aconj * HallX⁻¹ := by
    show (T⁻¹ * A * T) * A = A * (T⁻¹ * A * T) *
        (A⁻¹ * (T⁻¹ * A * T)⁻¹ * A * (T⁻¹ * A * T))⁻¹
    group
  rw [h]

/-- The definition of `HallY = A⁻¹ * HallX⁻¹ * A * HallX` in the free group already tells us
that `A * HallX = HallX * A * HallY` there, and hence in every quotient. -/
theorem mk_A_HallX :
    (PresentedGroup.mk relators (A * HallX) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallX * A * HallY) := by
  have h : (A * HallX : FreeGroup Generator) = HallX * A * HallY := by
    change A * HallX = HallX * A * (A⁻¹ * HallX⁻¹ * A * HallX)
    group
  rw [h]

/-- Reverse form of `mk_A_HallX`: `mk (HallX * A) = mk (A * HallX * HallY⁻¹)`. -/
theorem mk_HallX_A :
    (PresentedGroup.mk relators (HallX * A) : PresentedGroup relators) =
      PresentedGroup.mk relators (A * HallX * HallY⁻¹) := by
  have h : (HallX * A : FreeGroup Generator) = A * HallX * HallY⁻¹ := by
    change HallX * A = A * HallX * (A⁻¹ * HallX⁻¹ * A * HallX)⁻¹
    group
  rw [h]

/-- Reverse form of `mk_Aconj_A`: `mk (A * Aconj) = mk (Aconj * A * HallX)`. -/
theorem mk_A_Aconj :
    (PresentedGroup.mk relators (A * Aconj) : PresentedGroup relators) =
      PresentedGroup.mk relators (Aconj * A * HallX) := by
  have h : (A * Aconj : FreeGroup Generator) = Aconj * A * HallX := by
    show A * (T⁻¹ * A * T) = (T⁻¹ * A * T) * A *
        (A⁻¹ * (T⁻¹ * A * T)⁻¹ * A * (T⁻¹ * A * T))
    group
  rw [h]

/-- Moving `A⁻¹` past `Aconj⁻¹`: `mk (Aconj⁻¹ * A⁻¹) = mk (HallX⁻¹ * A⁻¹ * Aconj⁻¹)`.

Free-group inverse of `mk_A_Aconj`. -/
theorem mk_Aconjinv_Ainv :
    (PresentedGroup.mk relators (Aconj⁻¹ * A⁻¹) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallX⁻¹ * A⁻¹ * Aconj⁻¹) := by
  have h : (Aconj⁻¹ * A⁻¹ : FreeGroup Generator) = HallX⁻¹ * A⁻¹ * Aconj⁻¹ := by
    show (T⁻¹ * A * T)⁻¹ * A⁻¹ =
        (A⁻¹ * (T⁻¹ * A * T)⁻¹ * A * (T⁻¹ * A * T))⁻¹ * A⁻¹ * (T⁻¹ * A * T)⁻¹
    group
  rw [h]

/-- `mk` sends the third-relator commutator `⁅C, A⁆` to `1`. -/
theorem mk_commutator_C_A :
    (PresentedGroup.mk relators ⁅C, A⁆ : PresentedGroup relators) = 1 :=
  PresentedGroup.mk_eq_one_iff.mpr <|
    Subgroup.subset_normalClosure (by
      show ⁅C, A⁆ ∈ ({T * T, C * (⁅Aconj, ⁅A, Aconj⁆⁆)⁻¹, ⁅C, A⁆, ⁅C, Aconj⁆}
        : Set (FreeGroup Generator))
      simp)

/-- `mk` sends the fourth-relator commutator `⁅C, Aconj⁆` to `1`. -/
theorem mk_commutator_C_Aconj :
    (PresentedGroup.mk relators ⁅C, Aconj⁆ : PresentedGroup relators) = 1 :=
  PresentedGroup.mk_eq_one_iff.mpr <|
    Subgroup.subset_normalClosure (by
      show ⁅C, Aconj⁆ ∈ ({T * T, C * (⁅Aconj, ⁅A, Aconj⁆⁆)⁻¹, ⁅C, A⁆, ⁅C, Aconj⁆}
        : Set (FreeGroup Generator))
      simp)

/-- Centrality of `mk C` against `mk A`: `mk (C * A) = mk (A * C)`. -/
theorem mk_C_A_comm :
    (PresentedGroup.mk relators (C * A) : PresentedGroup relators) =
      PresentedGroup.mk relators (A * C) := by
  have hcomm' :
      ⁅(PresentedGroup.mk relators C : PresentedGroup relators),
        PresentedGroup.mk relators A⁆ = 1 := by
    have := mk_commutator_C_A
    simpa [map_commutatorElement] using this
  have hcomm := commutatorElement_eq_one_iff_commute.mp hcomm'
  show (PresentedGroup.mk relators C) * PresentedGroup.mk relators A =
    PresentedGroup.mk relators A * PresentedGroup.mk relators C
  exact hcomm

/-- Centrality of `mk C` against `mk Aconj`: `mk (C * Aconj) = mk (Aconj * C)`. -/
theorem mk_C_Aconj_comm :
    (PresentedGroup.mk relators (C * Aconj) : PresentedGroup relators) =
      PresentedGroup.mk relators (Aconj * C) := by
  have hcomm' :
      ⁅(PresentedGroup.mk relators C : PresentedGroup relators),
        PresentedGroup.mk relators Aconj⁆ = 1 := by
    have := mk_commutator_C_Aconj
    simpa [map_commutatorElement] using this
  have hcomm := commutatorElement_eq_one_iff_commute.mp hcomm'
  show (PresentedGroup.mk relators C) * PresentedGroup.mk relators Aconj =
    PresentedGroup.mk relators Aconj * PresentedGroup.mk relators C
  exact hcomm

/-!
### Shifts through the mathlib commutator `HallXC := ⁅A, Aconj⁆`

The mathlib commutator `⁅A, Aconj⁆ = A·Aconj·A⁻¹·Aconj⁻¹` is easier to shift past `A` and
`Aconj` than the Hall commutator `HallX`, because the commutator `[A, HallXC]_mathlib` is
exactly `C` by definition, and `C` is central. These shift lemmas are the building blocks for
the class-3 nilpotent structure of the presented group.
-/

/-- Free-group identity: `HallXC · A = C⁻¹ · A · HallXC`. This is immediate from
`C = A · HallXC · A⁻¹ · HallXC⁻¹` (definition of `C = ⁅A, HallXC⁆_mathlib`). -/
theorem freeGroup_HallXC_A :
    (⁅A, Aconj⁆ * A : FreeGroup Generator) = (⁅A, ⁅A, Aconj⁆⁆)⁻¹ * A * ⁅A, Aconj⁆ := by
  show (A * Aconj * A⁻¹ * Aconj⁻¹) * A =
       (A * (A * Aconj * A⁻¹ * Aconj⁻¹) * A⁻¹ * (A * Aconj * A⁻¹ * Aconj⁻¹)⁻¹)⁻¹ * A *
         (A * Aconj * A⁻¹ * Aconj⁻¹)
  group

/-- Free-group identity: `A · HallXC = C · HallXC · A`. -/
theorem freeGroup_A_HallXC :
    (A * ⁅A, Aconj⁆ : FreeGroup Generator) = ⁅A, ⁅A, Aconj⁆⁆ * ⁅A, Aconj⁆ * A := by
  show A * (A * Aconj * A⁻¹ * Aconj⁻¹) =
       (A * (A * Aconj * A⁻¹ * Aconj⁻¹) * A⁻¹ * (A * Aconj * A⁻¹ * Aconj⁻¹)⁻¹) *
         (A * Aconj * A⁻¹ * Aconj⁻¹) * A
  group

/-- Free-group identity: `Aconj · HallXC = ⁅Aconj, HallXC⁆ · HallXC · Aconj`. -/
theorem freeGroup_Aconj_HallXC :
    (Aconj * ⁅A, Aconj⁆ : FreeGroup Generator) =
      ⁅Aconj, ⁅A, Aconj⁆⁆ * ⁅A, Aconj⁆ * Aconj := by
  show (T⁻¹ * A * T) * (A * Aconj * A⁻¹ * Aconj⁻¹) =
       ((T⁻¹ * A * T) * (A * Aconj * A⁻¹ * Aconj⁻¹) * (T⁻¹ * A * T)⁻¹ *
           (A * Aconj * A⁻¹ * Aconj⁻¹)⁻¹) *
         (A * Aconj * A⁻¹ * Aconj⁻¹) * (T⁻¹ * A * T)
  group

/-- The second relator, applied: `mk C = mk ⁅Aconj, ⁅A, Aconj⁆⁆` in the presented group. -/
theorem mk_C_eq_mk_Engel :
    (PresentedGroup.mk relators C : PresentedGroup relators) =
      PresentedGroup.mk relators ⁅Aconj, ⁅A, Aconj⁆⁆ := by
  have hrel :
      (PresentedGroup.mk relators (C * (⁅Aconj, ⁅A, Aconj⁆⁆)⁻¹) :
          PresentedGroup relators) = 1 :=
    PresentedGroup.mk_eq_one_iff.mpr <|
      Subgroup.subset_normalClosure (by
        show C * (⁅Aconj, ⁅A, Aconj⁆⁆)⁻¹ ∈
          ({T * T, C * (⁅Aconj, ⁅A, Aconj⁆⁆)⁻¹, ⁅C, A⁆, ⁅C, Aconj⁆}
            : Set (FreeGroup Generator))
        simp)
  have := hrel
  rw [map_mul, map_inv, mul_inv_eq_one] at this
  exact this

/-- Inverse form of `mk_Aconj_A`: `mk (A⁻¹ * Aconj⁻¹) = mk (HallX * Aconj⁻¹ * A⁻¹)`. -/
theorem mk_Ainv_Aconjinv :
    (PresentedGroup.mk relators (A⁻¹ * Aconj⁻¹) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallX * Aconj⁻¹ * A⁻¹) := by
  have h : (A⁻¹ * Aconj⁻¹ : FreeGroup Generator) = HallX * Aconj⁻¹ * A⁻¹ := by
    show A⁻¹ * (T⁻¹ * A * T)⁻¹ =
      (A⁻¹ * (T⁻¹ * A * T)⁻¹ * A * (T⁻¹ * A * T)) * (T⁻¹ * A * T)⁻¹ * A⁻¹
    group
  rw [h]

/-- Inverse form of `mk_A_HallX`: `mk (HallX⁻¹ * A⁻¹) = mk (HallY⁻¹ * A⁻¹ * HallX⁻¹)`. -/
theorem mk_HallXinv_Ainv :
    (PresentedGroup.mk relators (HallX⁻¹ * A⁻¹) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallY⁻¹ * A⁻¹ * HallX⁻¹) := by
  have h : (HallX⁻¹ * A⁻¹ : FreeGroup Generator) = HallY⁻¹ * A⁻¹ * HallX⁻¹ := by
    change HallX⁻¹ * A⁻¹ =
      (A⁻¹ * HallX⁻¹ * A * HallX)⁻¹ * A⁻¹ * HallX⁻¹
    group
  rw [h]

/-- `mk C` commutes with `mk A⁻¹`: `mk (C * A⁻¹) = mk (A⁻¹ * C)`. -/
theorem mk_C_Ainv_comm :
    (PresentedGroup.mk relators (C * A⁻¹) : PresentedGroup relators) =
      PresentedGroup.mk relators (A⁻¹ * C) := by
  have hcomm : Commute (PresentedGroup.mk relators C : PresentedGroup relators)
      (PresentedGroup.mk relators A) := mk_C_A_comm
  have hinv := hcomm.inv_right
  show (PresentedGroup.mk relators C) * (PresentedGroup.mk relators A⁻¹) =
    (PresentedGroup.mk relators A⁻¹) * PresentedGroup.mk relators C
  rw [map_inv]; exact hinv

/-- `mk C` commutes with `mk Aconj⁻¹`: `mk (C * Aconj⁻¹) = mk (Aconj⁻¹ * C)`. -/
theorem mk_C_Aconjinv_comm :
    (PresentedGroup.mk relators (C * Aconj⁻¹) : PresentedGroup relators) =
      PresentedGroup.mk relators (Aconj⁻¹ * C) := by
  have hcomm : Commute (PresentedGroup.mk relators C : PresentedGroup relators)
      (PresentedGroup.mk relators Aconj) := mk_C_Aconj_comm
  have hinv := hcomm.inv_right
  show (PresentedGroup.mk relators C) * (PresentedGroup.mk relators Aconj⁻¹) =
    (PresentedGroup.mk relators Aconj⁻¹) * PresentedGroup.mk relators C
  rw [map_inv]; exact hinv

/-- `mk C` commutes with `mk HallXC := mk ⁅A, Aconj⁆`, since `HallXC` is a word in `A, Aconj`
and `mk C` commutes with both. -/
theorem mk_C_HallXC_comm :
    Commute (PresentedGroup.mk relators C : PresentedGroup relators)
      (PresentedGroup.mk relators ⁅A, Aconj⁆) := by
  have h : (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators) =
      PresentedGroup.mk relators A * PresentedGroup.mk relators Aconj *
      (PresentedGroup.mk relators A)⁻¹ * (PresentedGroup.mk relators Aconj)⁻¹ := by
    show PresentedGroup.mk relators (A * Aconj * A⁻¹ * Aconj⁻¹) = _
    rw [map_mul, map_mul, map_mul, map_inv, map_inv]
  rw [h]
  have ha : Commute (PresentedGroup.mk relators C : PresentedGroup relators)
      (PresentedGroup.mk relators A) := mk_C_A_comm
  have hb : Commute (PresentedGroup.mk relators C : PresentedGroup relators)
      (PresentedGroup.mk relators Aconj) := mk_C_Aconj_comm
  exact ((ha.mul_right hb).mul_right ha.inv_right).mul_right hb.inv_right

/-!
### Shift lemmas for `HallXC := ⁅A, Aconj⁆`

Using the free-group identities `freeGroup_HallXC_A`, `freeGroup_A_HallXC`,
`freeGroup_Aconj_HallXC` (which express `HallXC · A`, `A · HallXC`, `Aconj · HallXC` as
"corrections" involving `C`), plus centrality of `C` (against `A`, `Aconj`, `HallXC`), we obtain
clean shift laws in the presented group.
-/

/-- Shift of `HallXC` past `A`: `mk (HallXC · A) = mk (A · HallXC · C⁻¹)`. -/
theorem mk_HallXC_A_shift :
    (PresentedGroup.mk relators (⁅A, Aconj⁆ * A) : PresentedGroup relators) =
      PresentedGroup.mk relators (A * ⁅A, Aconj⁆ * C⁻¹) := by
  rw [freeGroup_HallXC_A]
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcA : Commute c a := mk_C_A_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  show c⁻¹ * a * xc = a * xc * c⁻¹
  have h1 : c⁻¹ * a = a * c⁻¹ := hcA.inv_left.eq
  have h2 : c⁻¹ * xc = xc * c⁻¹ := hcXC.inv_left.eq
  calc c⁻¹ * a * xc = a * c⁻¹ * xc := by rw [h1]
    _ = a * (c⁻¹ * xc) := by rw [mul_assoc]
    _ = a * (xc * c⁻¹) := by rw [h2]
    _ = a * xc * c⁻¹ := by rw [mul_assoc]

/-- Shift of `A` past `HallXC`: `mk (A · HallXC) = mk (HallXC · A · C)`. -/
theorem mk_A_HallXC_shift :
    (PresentedGroup.mk relators (A * ⁅A, Aconj⁆) : PresentedGroup relators) =
      PresentedGroup.mk relators (⁅A, Aconj⁆ * A * C) := by
  rw [freeGroup_A_HallXC]
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcA : Commute c a := mk_C_A_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  show c * xc * a = xc * a * c
  calc c * xc * a = xc * c * a := by rw [hcXC.eq]
    _ = xc * (c * a) := by rw [mul_assoc]
    _ = xc * (a * c) := by rw [hcA.eq]
    _ = xc * a * c := by rw [mul_assoc]

/-- Shift of `Aconj` past `HallXC`: `mk (Aconj · HallXC) = mk (HallXC · Aconj · C)`.

Uses `freeGroup_Aconj_HallXC`, `mk_C_eq_mk_Engel` (identifying `mk ⁅Aconj, HallXC⁆` with `mk C`),
and centrality of `C`. -/
theorem mk_Aconj_HallXC_shift :
    (PresentedGroup.mk relators (Aconj * ⁅A, Aconj⁆) : PresentedGroup relators) =
      PresentedGroup.mk relators (⁅A, Aconj⁆ * Aconj * C) := by
  rw [freeGroup_Aconj_HallXC]
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcB : Commute c b := mk_C_Aconj_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  have hEngel :
      (PresentedGroup.mk relators ⁅Aconj, ⁅A, Aconj⁆⁆ : PresentedGroup relators) = c :=
    mk_C_eq_mk_Engel.symm
  show PresentedGroup.mk relators ⁅Aconj, ⁅A, Aconj⁆⁆ * xc * b = xc * b * c
  rw [hEngel]
  calc c * xc * b = xc * c * b := by rw [hcXC.eq]
    _ = xc * (c * b) := by rw [mul_assoc]
    _ = xc * (b * c) := by rw [hcB.eq]
    _ = xc * b * c := by rw [mul_assoc]

/-- `T` conjugation on `HallX` returns `HallX⁻¹` at the presented-group level.

This reflects the fact that `T` acts on the abelianized commutator layer by swapping
`A ↔ Aconj`, and hence sending `X = ⁅A⁻¹, Aconj⁻¹⁆` to its inverse `⁅Aconj⁻¹, A⁻¹⁆`. -/
theorem mk_T_HallX_T :
    (PresentedGroup.mk relators (T * HallX * T) : PresentedGroup relators) =
      PresentedGroup.mk relators HallX⁻¹ := by
  set t := (PresentedGroup.mk relators T : PresentedGroup relators)
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  have htt : t * t = 1 := by
    have := mk_T_sq
    have hmul : (PresentedGroup.mk relators (T * T) : PresentedGroup relators) = t * t :=
      map_mul _ _ _
    rw [hmul] at this; exact this
  have ht_inv : t⁻¹ = t := inv_eq_of_mul_eq_one_left htt
  have hTAT : t * a * t = b := by
    have := mk_T_A_T
    have h1 : (PresentedGroup.mk relators (T * A * T) : PresentedGroup relators) = t * a * t := by
      rw [show (T * A * T : FreeGroup Generator) = T * A * T from rfl]
      rw [map_mul, map_mul]
    rw [h1] at this; exact this
  have hTBT : t * b * t = a := by
    have h : t * (t * a * t) * t = t * b * t := by rw [hTAT]
    have hcancel : t * (t * a * t) * t = a := by
      have step1 : t * (t * a * t) * t = (t * t) * a * (t * t) := by
        simp [mul_assoc]
      rw [step1, htt, one_mul, mul_one]
    rw [hcancel] at h; exact h.symm
  -- Inverse-swap identities: `t * a⁻¹ * t = b⁻¹`, `t * b⁻¹ * t = a⁻¹`.
  have hTAinvT : t * a⁻¹ * t = b⁻¹ := by
    have : (t * a * t)⁻¹ = b⁻¹ := congrArg (·⁻¹) hTAT
    rw [mul_inv_rev, mul_inv_rev, ht_inv] at this
    -- this : t * (a⁻¹ * t) = b⁻¹, need associativity fix
    rw [← mul_assoc] at this; exact this
  have hTBinvT : t * b⁻¹ * t = a⁻¹ := by
    have : (t * b * t)⁻¹ = a⁻¹ := congrArg (·⁻¹) hTBT
    rw [mul_inv_rev, mul_inv_rev, ht_inv] at this
    rw [← mul_assoc] at this; exact this
  -- Expand LHS and RHS in terms of `a, b, t`.
  have hlhs :
      (PresentedGroup.mk relators (T * HallX * T) : PresentedGroup relators)
        = t * (a⁻¹ * b⁻¹ * a * b) * t := by
    show PresentedGroup.mk relators (T * (A⁻¹ * Aconj⁻¹ * A * Aconj) * T) =
      t * (a⁻¹ * b⁻¹ * a * b) * t
    rw [map_mul, map_mul, map_mul, map_mul, map_mul, map_inv, map_inv]
  have hrhs :
      (PresentedGroup.mk relators HallX⁻¹ : PresentedGroup relators)
        = b⁻¹ * a⁻¹ * b * a := by
    show PresentedGroup.mk relators (Aconj⁻¹ * A⁻¹ * Aconj * A) = b⁻¹ * a⁻¹ * b * a
    rw [map_mul, map_mul, map_mul, map_inv, map_inv]
  rw [hlhs, hrhs]
  -- The core computation: insert `t * t = 1` between each factor and apply the swaps.
  have insert :
      t * (a⁻¹ * b⁻¹ * a * b) * t =
        (t * a⁻¹ * t) * (t * b⁻¹ * t) * (t * a * t) * (t * b * t) := by
    have e1 : t * (a⁻¹ * b⁻¹ * a * b) * t =
        t * a⁻¹ * (t * t) * b⁻¹ * (t * t) * a * (t * t) * b * t := by
      rw [htt]; group
    rw [e1]; group
  rw [insert, hTAinvT, hTBinvT, hTAT, hTBT]

/-- T-conjugation on `HallY`: at the presented-group level,
`T * HallY * T = Aconj⁻¹ * HallX * Aconj * HallX⁻¹`.

This is the analog of `mk_T_HallX_T`, expressing the effect of T-conjugation on the
Hall-convention class-3 commutator `HallY = A⁻¹ * HallX⁻¹ * A * HallX`. It follows from
inserting `T² = 1` between the four factors of `HallY` and applying the swaps
`T * A * T = Aconj`, `T * A⁻¹ * T = Aconj⁻¹`, `T * HallX * T = HallX⁻¹`,
`T * HallX⁻¹ * T = HallX`. -/
theorem mk_T_HallY_T :
    (PresentedGroup.mk relators (T * HallY * T) : PresentedGroup relators) =
      PresentedGroup.mk relators (Aconj⁻¹ * HallX * Aconj * HallX⁻¹) := by
  set t := (PresentedGroup.mk relators T : PresentedGroup relators)
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  have htt : t * t = 1 := by
    have := mk_T_sq
    have hmul : (PresentedGroup.mk relators (T * T) : PresentedGroup relators) = t * t :=
      map_mul _ _ _
    rw [hmul] at this; exact this
  -- Four T-conjugation identities.
  have hTAT : t * a * t = b := by
    have := mk_T_A_T
    have h1 : (PresentedGroup.mk relators (T * A * T) : PresentedGroup relators) = t * a * t := by
      rw [map_mul, map_mul]
    rw [h1] at this; exact this
  have hTAinvT : t * a⁻¹ * t = b⁻¹ := by
    have : (t * a * t)⁻¹ = b⁻¹ := congrArg (·⁻¹) hTAT
    have ht_inv : t⁻¹ = t := inv_eq_of_mul_eq_one_left htt
    rw [mul_inv_rev, mul_inv_rev, ht_inv] at this
    rw [← mul_assoc] at this; exact this
  have hTHXT : t * x * t = x⁻¹ := by
    have := mk_T_HallX_T
    have h1 : (PresentedGroup.mk relators (T * HallX * T) : PresentedGroup relators)
        = t * x * t := by
      rw [map_mul, map_mul]
    have h2 : (PresentedGroup.mk relators HallX⁻¹ : PresentedGroup relators) = x⁻¹ := by
      rw [map_inv]
    rw [h1, h2] at this; exact this
  have hTHXinvT : t * x⁻¹ * t = x := by
    have : (t * x * t)⁻¹ = (x⁻¹ : PresentedGroup relators)⁻¹ := congrArg (·⁻¹) hTHXT
    have ht_inv : t⁻¹ = t := inv_eq_of_mul_eq_one_left htt
    rw [mul_inv_rev, mul_inv_rev, ht_inv, inv_inv] at this
    rw [← mul_assoc] at this; exact this
  -- Expand LHS in `a, b, x, t`.
  have hlhs :
      (PresentedGroup.mk relators (T * HallY * T) : PresentedGroup relators)
        = t * (a⁻¹ * x⁻¹ * a * x) * t := by
    show PresentedGroup.mk relators (T * (A⁻¹ * HallX⁻¹ * A * HallX) * T) =
      t * (a⁻¹ * x⁻¹ * a * x) * t
    rw [map_mul, map_mul, map_mul, map_mul, map_mul, map_inv, map_inv]
  have hrhs :
      (PresentedGroup.mk relators (Aconj⁻¹ * HallX * Aconj * HallX⁻¹)
          : PresentedGroup relators)
        = b⁻¹ * x * b * x⁻¹ := by
    rw [map_mul, map_mul, map_mul, map_inv, map_inv]
  rw [hlhs, hrhs]
  -- Insert `t * t = 1` between the four factors and apply the swaps.
  have insert :
      t * (a⁻¹ * x⁻¹ * a * x) * t =
        (t * a⁻¹ * t) * (t * x⁻¹ * t) * (t * a * t) * (t * x * t) := by
    have e1 : t * (a⁻¹ * x⁻¹ * a * x) * t =
        t * a⁻¹ * (t * t) * x⁻¹ * (t * t) * a * (t * t) * x * t := by
      rw [htt]; group
    rw [e1]; group
  rw [insert, hTAinvT, hTHXinvT, hTAT, hTHXT]

/-!
### Deriving `mk HallX = mk (HallXC · C⁻²)` and `mk HallY = mk C`

The Hall commutator `HallX = ⁅A, Aconj⁆_Hall` and the mathlib commutator
`HallXC = ⁅A, Aconj⁆_mathlib` differ by a specific central class-3 element in the presented
group. The derivation uses that `mk (Aconj · A)` has two representations: the free-group
identity `mk_Aconj_A` gives `mk (A · Aconj · HallX⁻¹)`, while chaining shift lemmas gives
`mk (A · Aconj · HallXC⁻¹ · C²)`. Equating both determines `mk HallX = mk (HallXC · C⁻²)`.

Once this is available, `mk HallY = mk C` follows from a short calculation using the shift
lemmas.
-/

/-- Second shift of `HallXC⁻¹` past `A`: `mk (HallXC⁻¹ · A) = mk (C · A · HallXC⁻¹)`.

Derived from `mk_HallXC_A_shift` by manipulation using centrality of `C`. -/
theorem mk_HallXCinv_A :
    (PresentedGroup.mk relators (⁅A, Aconj⁆⁻¹ * A) : PresentedGroup relators) =
      PresentedGroup.mk relators (C * A * ⁅A, Aconj⁆⁻¹) := by
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcA : Commute c a := mk_C_A_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  have hshift : xc * a = a * xc * c⁻¹ := by
    have := mk_HallXC_A_shift
    have h1 : (PresentedGroup.mk relators (⁅A, Aconj⁆ * A) : PresentedGroup relators)
        = xc * a := by rw [map_mul]
    have h2 : (PresentedGroup.mk relators (A * ⁅A, Aconj⁆ * C⁻¹) :
        PresentedGroup relators) = a * xc * c⁻¹ := by rw [map_mul, map_mul, map_inv]
    rw [h1, h2] at this; exact this
  show PresentedGroup.mk relators ⁅A, Aconj⁆⁻¹ * PresentedGroup.mk relators A =
      PresentedGroup.mk relators C * PresentedGroup.mk relators A *
        PresentedGroup.mk relators ⁅A, Aconj⁆⁻¹
  simp only [map_inv]
  change xc⁻¹ * a = c * a * xc⁻¹
  -- From xc·a = a·xc·c⁻¹:  left-mult by xc⁻¹ gives a = xc⁻¹·a·xc·c⁻¹.
  -- Right-mult by c gives a·c = xc⁻¹·a·xc, i.e. c·a = xc⁻¹·a·xc.
  -- Right-mult by xc⁻¹ gives c·a·xc⁻¹ = xc⁻¹·a.
  have h1 : a = xc⁻¹ * a * xc * c⁻¹ := by
    calc a = xc⁻¹ * (xc * a) := by rw [← mul_assoc, inv_mul_cancel, one_mul]
      _ = xc⁻¹ * (a * xc * c⁻¹) := by rw [hshift]
      _ = xc⁻¹ * a * xc * c⁻¹ := by rw [← mul_assoc, ← mul_assoc]
  have h2 : a * c = xc⁻¹ * a * xc := by
    have := congrArg (· * c) h1
    simp only [mul_assoc, inv_mul_cancel, mul_one] at this
    exact this
  have h3 : c * a * xc⁻¹ = xc⁻¹ * a := by
    have hca : c * a = a * c := hcA.eq
    rw [hca, h2]
    rw [mul_assoc, mul_inv_cancel, mul_one]
  exact h3.symm

/-- Symmetric shift for `Aconj`: `mk (HallXC⁻¹ · Aconj) = mk (C · Aconj · HallXC⁻¹)`.

Derived from `mk_Aconj_HallXC_shift` the same way `mk_HallXCinv_A` is derived from
`mk_HallXC_A_shift`. -/
theorem mk_HallXCinv_Aconj :
    (PresentedGroup.mk relators (⁅A, Aconj⁆⁻¹ * Aconj) : PresentedGroup relators) =
      PresentedGroup.mk relators (C * Aconj * ⁅A, Aconj⁆⁻¹) := by
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcB : Commute c b := mk_C_Aconj_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  have hshift : b * xc = xc * b * c := by
    have := mk_Aconj_HallXC_shift
    have h1 : (PresentedGroup.mk relators (Aconj * ⁅A, Aconj⁆) : PresentedGroup relators)
        = b * xc := by rw [map_mul]
    have h2 : (PresentedGroup.mk relators (⁅A, Aconj⁆ * Aconj * C) :
        PresentedGroup relators) = xc * b * c := by rw [map_mul, map_mul]
    rw [h1, h2] at this; exact this
  show PresentedGroup.mk relators ⁅A, Aconj⁆⁻¹ * PresentedGroup.mk relators Aconj =
      PresentedGroup.mk relators C * PresentedGroup.mk relators Aconj *
        PresentedGroup.mk relators ⁅A, Aconj⁆⁻¹
  simp only [map_inv]
  change xc⁻¹ * b = c * b * xc⁻¹
  -- From b·xc = xc·b·c: symmetric derivation.
  -- xc·b·c = b·xc  ⟹  xc·b = b·xc·c⁻¹  [right-mult by c⁻¹]
  -- Now this matches the pattern from mk_HallXCinv_A with (b, +c⁻¹) instead of (a, +c⁻¹)?
  -- Actually here we have b·xc = xc·b·c, which is xc·b = b·xc·c⁻¹ after swap.
  -- Then follow the same steps as before with the sign convention swapped.
  have hshift' : xc * b = b * xc * c⁻¹ := by
    have h := hshift
    -- b*xc = xc*b*c  ⟹  b*xc*c⁻¹ = xc*b
    have h2 : b * xc * c⁻¹ = xc * b := by
      rw [h]; rw [mul_assoc, mul_inv_cancel, mul_one]
    exact h2.symm
  have h1 : b = xc⁻¹ * b * xc * c⁻¹ := by
    calc b = xc⁻¹ * (xc * b) := by rw [← mul_assoc, inv_mul_cancel, one_mul]
      _ = xc⁻¹ * (b * xc * c⁻¹) := by rw [hshift']
      _ = xc⁻¹ * b * xc * c⁻¹ := by rw [← mul_assoc, ← mul_assoc]
  have h2 : b * c = xc⁻¹ * b * xc := by
    have := congrArg (· * c) h1
    simp only [mul_assoc, inv_mul_cancel, mul_one] at this
    exact this
  have h3 : c * b * xc⁻¹ = xc⁻¹ * b := by
    have hcb : c * b = b * c := hcB.eq
    rw [hcb, h2, mul_assoc, mul_inv_cancel, mul_one]
  exact h3.symm

/-- Free-group identity: `Aconj · A = ⁅A, Aconj⁆⁻¹ · A · Aconj`. -/
theorem freeGroup_Aconj_A_HallXC :
    (Aconj * A : FreeGroup Generator) = ⁅A, Aconj⁆⁻¹ * A * Aconj := by
  show T⁻¹ * A * T * A = (A * (T⁻¹ * A * T) * A⁻¹ * (T⁻¹ * A * T)⁻¹)⁻¹ * A * (T⁻¹ * A * T)
  group

/-- Second derivation of `mk (Aconj · A)`: via the `HallXC` shift chain. -/
theorem mk_Aconj_A_HallXC :
    (PresentedGroup.mk relators (Aconj * A) : PresentedGroup relators) =
      PresentedGroup.mk relators (A * Aconj * ⁅A, Aconj⁆⁻¹ * C * C) := by
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcA : Commute c a := mk_C_A_comm
  have hcB : Commute c b := mk_C_Aconj_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  -- Step 1: rewrite via free-group identity.
  rw [freeGroup_Aconj_A_HallXC]
  -- Now goal: mk(HallXC⁻¹ · A · Aconj) = mk(A · Aconj · HallXC⁻¹ · C · C)
  have s1 : (PresentedGroup.mk relators (⁅A, Aconj⁆⁻¹ * A * Aconj) : PresentedGroup relators)
      = xc⁻¹ * a * b := by rw [map_mul, map_mul, map_inv]
  have s2 : (PresentedGroup.mk relators (A * Aconj * ⁅A, Aconj⁆⁻¹ * C * C) :
      PresentedGroup relators) = a * b * xc⁻¹ * c * c := by
    rw [map_mul, map_mul, map_mul, map_mul, map_inv]
  rw [s1, s2]
  -- Use mk_HallXCinv_A: xc⁻¹ * a = c * a * xc⁻¹
  have hA : xc⁻¹ * a = c * a * xc⁻¹ := by
    have := mk_HallXCinv_A
    have h1 : (PresentedGroup.mk relators (⁅A, Aconj⁆⁻¹ * A) : PresentedGroup relators)
        = xc⁻¹ * a := by rw [map_mul, map_inv]
    have h2 : (PresentedGroup.mk relators (C * A * ⁅A, Aconj⁆⁻¹) :
        PresentedGroup relators) = c * a * xc⁻¹ := by rw [map_mul, map_mul, map_inv]
    rw [h1, h2] at this; exact this
  have hB : xc⁻¹ * b = c * b * xc⁻¹ := by
    have := mk_HallXCinv_Aconj
    have h1 : (PresentedGroup.mk relators (⁅A, Aconj⁆⁻¹ * Aconj) : PresentedGroup relators)
        = xc⁻¹ * b := by rw [map_mul, map_inv]
    have h2 : (PresentedGroup.mk relators (C * Aconj * ⁅A, Aconj⁆⁻¹) :
        PresentedGroup relators) = c * b * xc⁻¹ := by rw [map_mul, map_mul, map_inv]
    rw [h1, h2] at this; exact this
  -- xc⁻¹ · a · b = a · b · xc⁻¹ · c · c
  have hcc_a : Commute (c * c) a := hcA.mul_left hcA
  have hcc_b : Commute (c * c) b := hcB.mul_left hcB
  have hcc_xc : Commute (c * c) xc := hcXC.mul_left hcXC
  have hcc_xcinv : Commute (c * c) xc⁻¹ := hcc_xc.inv_right
  calc xc⁻¹ * a * b
      = (xc⁻¹ * a) * b := by rw [mul_assoc]
    _ = (c * a * xc⁻¹) * b := by rw [hA]
    _ = c * a * (xc⁻¹ * b) := by simp [mul_assoc]
    _ = c * a * (c * b * xc⁻¹) := by rw [hB]
    _ = (c * a * c) * (b * xc⁻¹) := by simp [mul_assoc]
    _ = (c * (c * a)) * (b * xc⁻¹) := by rw [mul_assoc c a c, hcA.eq]
    _ = (c * c) * a * b * xc⁻¹ := by simp [mul_assoc]
    _ = a * (c * c) * b * xc⁻¹ := by rw [← hcc_a.eq]
    _ = a * b * (c * c) * xc⁻¹ := by rw [mul_assoc a (c*c) b, hcc_b.eq, ← mul_assoc]
    _ = a * b * (xc⁻¹ * (c * c)) := by rw [mul_assoc, hcc_xcinv.eq]
    _ = a * b * xc⁻¹ * c * c := by simp [mul_assoc]

/-- `mk HallX = mk (⁅A, Aconj⁆ · C⁻² )`. Combines the two derivations of `mk (Aconj · A)`. -/
theorem mk_HallX_eq_HallXC_Cinv_sq :
    (PresentedGroup.mk relators HallX : PresentedGroup relators) =
      PresentedGroup.mk relators (⁅A, Aconj⁆ * C⁻¹ * C⁻¹) := by
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  -- Two derivations of mk(Aconj·A):
  -- (i)  mk_Aconj_A         : mk(Aconj·A) = mk(A·Aconj·HallX⁻¹) = a·b·x⁻¹
  -- (ii) mk_Aconj_A_HallXC  : mk(Aconj·A) = mk(A·Aconj·HallXC⁻¹·C·C) = a·b·xc⁻¹·c·c
  have e1 : b * a = a * b * x⁻¹ := by
    have := mk_Aconj_A
    have h1 : (PresentedGroup.mk relators (Aconj * A) : PresentedGroup relators)
        = b * a := by rw [map_mul]
    have h2 : (PresentedGroup.mk relators (A * Aconj * HallX⁻¹) :
        PresentedGroup relators) = a * b * x⁻¹ := by rw [map_mul, map_mul, map_inv]
    rw [h1, h2] at this; exact this
  have e2 : b * a = a * b * xc⁻¹ * c * c := by
    have := mk_Aconj_A_HallXC
    have h1 : (PresentedGroup.mk relators (Aconj * A) : PresentedGroup relators)
        = b * a := by rw [map_mul]
    have h2 : (PresentedGroup.mk relators (A * Aconj * ⁅A, Aconj⁆⁻¹ * C * C) :
        PresentedGroup relators) = a * b * xc⁻¹ * c * c := by
      rw [map_mul, map_mul, map_mul, map_mul, map_inv]
    rw [h1, h2] at this; exact this
  have eq : a * b * x⁻¹ = a * b * xc⁻¹ * c * c := e1.symm.trans e2
  -- Cancel a·b on the left.
  have hcancel : x⁻¹ = xc⁻¹ * c * c := by
    have hab : a * b * x⁻¹ = (a * b) * x⁻¹ := by rfl
    have heq' : (a * b) * x⁻¹ = (a * b) * (xc⁻¹ * c * c) := by
      rw [eq]; simp [mul_assoc]
    exact mul_left_cancel heq'
  -- Invert.
  have hcXC : Commute c xc := mk_C_HallXC_comm
  have hinv : x = c⁻¹ * c⁻¹ * xc := by
    have := congrArg (·⁻¹) hcancel
    simp only [mul_inv_rev, inv_inv] at this
    -- this : x = c⁻¹ * c⁻¹ * xc  (after inversion)
    exact this
  show x = xc * c⁻¹ * c⁻¹
  rw [hinv]
  -- c⁻¹·c⁻¹·xc = xc·c⁻¹·c⁻¹  (c⁻¹ central)
  have : Commute (c⁻¹ * c⁻¹) xc := (hcXC.inv_left.mul_left hcXC.inv_left)
  rw [this.eq, mul_assoc]

/-- The key class-3 identity: `mk HallY = mk C` in the presented group. -/
theorem mk_HallY_eq_C :
    (PresentedGroup.mk relators HallY : PresentedGroup relators) =
      PresentedGroup.mk relators C := by
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcA : Commute c a := mk_C_A_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  -- Step A: mk HallY = a⁻¹ · x⁻¹ · a · x  by definition.
  have step0 : (PresentedGroup.mk relators HallY : PresentedGroup relators) =
      a⁻¹ * x⁻¹ * a * x := by
    show (PresentedGroup.mk relators (A⁻¹ * HallX⁻¹ * A * HallX) : PresentedGroup relators) =
      a⁻¹ * x⁻¹ * a * x
    rw [map_mul, map_mul, map_mul, map_inv, map_inv]
  -- Step B: substitute x = xc · c⁻² and simplify.
  have hx : x = xc * c⁻¹ * c⁻¹ := mk_HallX_eq_HallXC_Cinv_sq
  have hxinv : x⁻¹ = c * c * xc⁻¹ := by
    rw [hx]; simp [mul_inv_rev, mul_assoc]
  rw [step0, hxinv, hx]
  -- Now goal: a⁻¹ · (c·c·xc⁻¹) · a · (xc·c⁻¹·c⁻¹) = c
  -- Use centrality of c to move c·c and c⁻¹·c⁻¹ to the end and cancel.
  have hcAinv : Commute c a⁻¹ := hcA.inv_right
  have hcinv_xc : Commute c⁻¹ xc := hcXC.inv_left
  -- Rewrite as (c·c) · (a⁻¹·xc⁻¹·a·xc) · (c⁻¹·c⁻¹) using centrality, then note c·c · X · c⁻¹·c⁻¹ = X when everything commutes with c.
  have key : a⁻¹ * (c * c * xc⁻¹) * a * (xc * c⁻¹ * c⁻¹) =
      (c * c) * (a⁻¹ * xc⁻¹ * a * xc) * (c⁻¹ * c⁻¹) := by
    have h1 : a⁻¹ * (c * c * xc⁻¹) = c * c * a⁻¹ * xc⁻¹ := by
      have hcc_a : Commute (c * c) a⁻¹ := hcAinv.mul_left hcAinv
      rw [show a⁻¹ * (c * c * xc⁻¹) = a⁻¹ * (c * c) * xc⁻¹ from by simp [mul_assoc],
          ← hcc_a.eq]
    have h2 : (xc * c⁻¹ * c⁻¹) = c⁻¹ * c⁻¹ * xc := by
      have hcc_xc : Commute (c⁻¹ * c⁻¹) xc := hcinv_xc.mul_left hcinv_xc
      have := hcc_xc.eq  -- c⁻¹·c⁻¹·xc = xc·(c⁻¹·c⁻¹)
      rw [show xc * c⁻¹ * c⁻¹ = xc * (c⁻¹ * c⁻¹) from by rw [mul_assoc], ← this]
    calc a⁻¹ * (c * c * xc⁻¹) * a * (xc * c⁻¹ * c⁻¹)
        = (c * c * a⁻¹ * xc⁻¹) * a * (xc * c⁻¹ * c⁻¹) := by rw [h1]
      _ = c * c * (a⁻¹ * xc⁻¹ * a) * (xc * c⁻¹ * c⁻¹) := by
          simp [mul_assoc]
      _ = c * c * (a⁻¹ * xc⁻¹ * a) * (xc * (c⁻¹ * c⁻¹)) := by
          rw [show xc * c⁻¹ * c⁻¹ = xc * (c⁻¹ * c⁻¹) from by rw [mul_assoc]]
      _ = c * c * (a⁻¹ * xc⁻¹ * a * xc) * (c⁻¹ * c⁻¹) := by
          simp [mul_assoc]
  rw [key]
  -- Now reduce the inner commutator: a⁻¹ · xc⁻¹ · a · xc = c.
  have inner : a⁻¹ * xc⁻¹ * a * xc = c := by
    -- From mk_HallXC_A_shift: xc·a = a·xc·c⁻¹  ⟹  a⁻¹·xc·a = xc·c⁻¹.
    have hshift : xc * a = a * xc * c⁻¹ := by
      have := mk_HallXC_A_shift
      have h1 : (PresentedGroup.mk relators (⁅A, Aconj⁆ * A) : PresentedGroup relators)
          = xc * a := by rw [map_mul]
      have h2 : (PresentedGroup.mk relators (A * ⁅A, Aconj⁆ * C⁻¹) :
          PresentedGroup relators) = a * xc * c⁻¹ := by rw [map_mul, map_mul, map_inv]
      rw [h1, h2] at this; exact this
    -- a⁻¹ * (xc * a) = a⁻¹ * (a * xc * c⁻¹) = xc * c⁻¹
    have hconj : a⁻¹ * xc * a = xc * c⁻¹ := by
      calc a⁻¹ * xc * a = a⁻¹ * (xc * a) := by rw [mul_assoc]
        _ = a⁻¹ * (a * xc * c⁻¹) := by rw [hshift]
        _ = xc * c⁻¹ := by rw [show a⁻¹ * (a * xc * c⁻¹) = (a⁻¹ * a) * xc * c⁻¹ from by
                                simp [mul_assoc], inv_mul_cancel, one_mul]
    -- Invert to get a⁻¹ · xc⁻¹ · a = c · xc⁻¹.
    have hconj_inv : a⁻¹ * xc⁻¹ * a = c * xc⁻¹ := by
      have := congrArg (·⁻¹) hconj
      simp only [mul_inv_rev, inv_inv] at this
      -- this : a⁻¹·xc⁻¹·a = c·xc⁻¹  (after inversion)
      -- Actually (a⁻¹·xc·a)⁻¹ = a⁻¹·xc⁻¹·a, and (xc·c⁻¹)⁻¹ = c·xc⁻¹.
      convert this using 1 <;> group
    -- Now right-mult by xc.
    calc a⁻¹ * xc⁻¹ * a * xc = (a⁻¹ * xc⁻¹ * a) * xc := by rw [mul_assoc]
      _ = c * xc⁻¹ * xc := by rw [hconj_inv]
      _ = c := by rw [mul_assoc, inv_mul_cancel, mul_one]
  rw [inner]
  -- Now: c * c * c * (c⁻¹ * c⁻¹) = c
  rw [show c * c * c * (c⁻¹ * c⁻¹) = c * (c * (c * c⁻¹) * c⁻¹) from by simp [mul_assoc]]
  simp

/-- `mk HallY` commutes with `mk A`, since `mk HallY = mk C` and `mk C` is central. -/
theorem mk_HallY_A_comm :
    Commute (PresentedGroup.mk relators HallY : PresentedGroup relators)
      (PresentedGroup.mk relators A) := by
  rw [mk_HallY_eq_C]; exact mk_C_A_comm

/-- `mk HallY` commutes with `mk Aconj`. -/
theorem mk_HallY_Aconj_comm :
    Commute (PresentedGroup.mk relators HallY : PresentedGroup relators)
      (PresentedGroup.mk relators Aconj) := by
  rw [mk_HallY_eq_C]; exact mk_C_Aconj_comm

/-- `mk HallY` commutes with `mk ⁅A, Aconj⁆` (the mathlib commutator `HallXC`). -/
theorem mk_HallY_HallXC_comm :
    Commute (PresentedGroup.mk relators HallY : PresentedGroup relators)
      (PresentedGroup.mk relators ⁅A, Aconj⁆) := by
  rw [mk_HallY_eq_C]; exact mk_C_HallXC_comm

/-!
### Cross-commutation `[Aconj, HallX] = HallY`

The class-3 commutator identity `mk (Aconj · HallX · Aconj⁻¹ · HallX⁻¹) = mk HallY` follows
from `mk C = mk ⁅Aconj, HallXC⁆` (a relator) via substitution of `mk HallX = mk (HallXC · C⁻²)`.
This unlocks all Aconj/HallX shift lemmas needed for Malcev collection.
-/

/-- The class-3 commutator identity: `mk (Aconj · HallX · Aconj⁻¹ · HallX⁻¹) = mk C = mk HallY`. -/
theorem mk_commutator_Aconj_HallX_eq_HallY :
    (PresentedGroup.mk relators (Aconj * HallX * Aconj⁻¹ * HallX⁻¹) : PresentedGroup relators) =
      PresentedGroup.mk relators HallY := by
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  set xc := (PresentedGroup.mk relators ⁅A, Aconj⁆ : PresentedGroup relators)
  set c := (PresentedGroup.mk relators C : PresentedGroup relators)
  have hcB : Commute c b := mk_C_Aconj_comm
  have hcXC : Commute c xc := mk_C_HallXC_comm
  have hcBinv : Commute c b⁻¹ := hcB.inv_right
  -- LHS = b · x · b⁻¹ · x⁻¹.
  have hlhs : (PresentedGroup.mk relators (Aconj * HallX * Aconj⁻¹ * HallX⁻¹) :
      PresentedGroup relators) = b * x * b⁻¹ * x⁻¹ := by
    rw [map_mul, map_mul, map_mul, map_inv, map_inv]
  rw [hlhs, mk_HallY_eq_C]
  -- Substitute x = xc·c⁻¹·c⁻¹, x⁻¹ = c·c·xc⁻¹.
  have hx : x = xc * c⁻¹ * c⁻¹ := mk_HallX_eq_HallXC_Cinv_sq
  have hxinv : x⁻¹ = c * c * xc⁻¹ := by rw [hx]; simp [mul_inv_rev, mul_assoc]
  rw [hxinv, hx]
  -- b · (xc·c⁻¹·c⁻¹) · b⁻¹ · (c·c·xc⁻¹)
  -- Move c⁻¹·c⁻¹ past b⁻¹ (central), c·c past xc⁻¹ (central), collect c⁻²·c² = 1.
  have hcc_binv : Commute (c⁻¹ * c⁻¹) b⁻¹ := hcBinv.inv_left.mul_left hcBinv.inv_left
  have hcinv_xc : Commute c⁻¹ xc := hcXC.inv_left
  have hcc_xc : Commute (c⁻¹ * c⁻¹) xc := hcinv_xc.mul_left hcinv_xc
  -- We want to show b·xc·c⁻¹·c⁻¹·b⁻¹·c·c·xc⁻¹ = c.
  -- Move c⁻¹·c⁻¹ past b⁻¹: get b·xc·b⁻¹·(c⁻¹·c⁻¹)·c·c·xc⁻¹ = b·xc·b⁻¹·xc⁻¹.
  -- Now use inner identity b·xc·b⁻¹·xc⁻¹ = c? No, we need to check.
  -- Actually from mk_C_eq_mk_Engel: mk C = mk ⁅Aconj, ⁅A, Aconj⁆⁆ = mk (b·xc·b⁻¹·xc⁻¹).
  have hmkC : c = b * xc * b⁻¹ * xc⁻¹ := by
    have := mk_C_eq_mk_Engel
    have h : (PresentedGroup.mk relators ⁅Aconj, ⁅A, Aconj⁆⁆ : PresentedGroup relators) =
        b * xc * b⁻¹ * xc⁻¹ := by
      show PresentedGroup.mk relators (Aconj * ⁅A, Aconj⁆ * Aconj⁻¹ * ⁅A, Aconj⁆⁻¹) = _
      rw [map_mul, map_mul, map_mul, map_inv, map_inv]
    rw [h] at this; exact this
  -- Now the calc:
  calc b * (xc * c⁻¹ * c⁻¹) * b⁻¹ * (c * c * xc⁻¹)
      = b * xc * (c⁻¹ * c⁻¹) * b⁻¹ * (c * c * xc⁻¹) := by simp [mul_assoc]
    _ = b * xc * (b⁻¹ * (c⁻¹ * c⁻¹)) * (c * c * xc⁻¹) := by
        rw [show b * xc * (c⁻¹ * c⁻¹) * b⁻¹ = b * xc * ((c⁻¹ * c⁻¹) * b⁻¹) from by simp [mul_assoc],
            hcc_binv.eq]
    _ = b * xc * b⁻¹ * ((c⁻¹ * c⁻¹) * (c * c)) * xc⁻¹ := by simp [mul_assoc]
    _ = b * xc * b⁻¹ * xc⁻¹ := by
        rw [show (c⁻¹ * c⁻¹) * (c * c) = 1 from by group, mul_one]
    _ = c := hmkC.symm

/-- `mk HallY` commutes with `mk HallX`. -/
theorem mk_HallY_HallX_comm :
    Commute (PresentedGroup.mk relators HallY : PresentedGroup relators)
      (PresentedGroup.mk relators HallX) := by
  rw [mk_HallY_eq_C, mk_HallX_eq_HallXC_Cinv_sq]
  have h1 : Commute (PresentedGroup.mk relators C : PresentedGroup relators)
      (PresentedGroup.mk relators ⁅A, Aconj⁆) := mk_C_HallXC_comm
  have h2 : Commute (PresentedGroup.mk relators C : PresentedGroup relators)
      (PresentedGroup.mk relators C)⁻¹ :=
    (Commute.refl _).inv_right
  exact (h1.mul_right h2).mul_right h2

/-- Basic shift: `mk (Aconj · HallX) = mk (HallX · Aconj · HallY)`. -/
theorem mk_Aconj_HallX :
    (PresentedGroup.mk relators (Aconj * HallX) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallX * Aconj * HallY) := by
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  set y := (PresentedGroup.mk relators HallY : PresentedGroup relators)
  have hcomm : b * x * b⁻¹ * x⁻¹ = y := by
    have := mk_commutator_Aconj_HallX_eq_HallY
    have h : (PresentedGroup.mk relators (Aconj * HallX * Aconj⁻¹ * HallX⁻¹)
        : PresentedGroup relators) = b * x * b⁻¹ * x⁻¹ := by
      rw [map_mul, map_mul, map_mul, map_inv, map_inv]
    rw [h] at this; exact this
  have hYX : Commute y x := mk_HallY_HallX_comm
  have hYB : Commute y b := mk_HallY_Aconj_comm
  have step : b * x = y * x * b := by
    have h2 : b * x * b⁻¹ * x⁻¹ * (x * b) = y * (x * b) := by rw [hcomm]
    rw [show b * x * b⁻¹ * x⁻¹ * (x * b) = b * x * b⁻¹ * (x⁻¹ * x) * b from by simp [mul_assoc],
        inv_mul_cancel, mul_one, mul_assoc, inv_mul_cancel, mul_one] at h2
    rw [h2]; simp [mul_assoc]
  show b * x = x * b * y
  rw [step, hYX.eq, mul_assoc, hYB.eq, ← mul_assoc]

/-- Reverse shift: `mk (HallX · Aconj) = mk (Aconj · HallX · HallY⁻¹)`. -/
theorem mk_HallX_Aconj :
    (PresentedGroup.mk relators (HallX * Aconj) : PresentedGroup relators) =
      PresentedGroup.mk relators (Aconj * HallX * HallY⁻¹) := by
  set b := (PresentedGroup.mk relators Aconj : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  set y := (PresentedGroup.mk relators HallY : PresentedGroup relators)
  -- From mk_Aconj_HallX: b·x = x·b·y  ⟹  x·b = b·x·y⁻¹.
  have h : b * x = x * b * y := by
    have := mk_Aconj_HallX
    have hl : (PresentedGroup.mk relators (Aconj * HallX) : PresentedGroup relators) = b * x := by
      rw [map_mul]
    have hr : (PresentedGroup.mk relators (HallX * Aconj * HallY) : PresentedGroup relators)
        = x * b * y := by rw [map_mul, map_mul]
    rw [hl, hr] at this; exact this
  have hYX : Commute y x := mk_HallY_HallX_comm
  have hYB : Commute y b := mk_HallY_Aconj_comm
  show x * b = b * x * y⁻¹
  -- b·x·y⁻¹ = x·b·y·y⁻¹ = x·b
  have : b * x * y⁻¹ = x * b := by
    rw [h]; simp [mul_assoc]
  exact this.symm

/-!
### Iterated shifts through integer powers

The single-step shifts above can be iterated over integer powers of A, Aconj, HallX. Since
mk HallY is central, HallY-corrections accumulate simply. These iterated shifts are the
building blocks of Malcev collection for hallNormalWord multiplication.
-/

/-- Iterated shift: `mk (A^n · HallX) = mk (HallX · A^n · HallY^n)` for natural n. -/
theorem mk_A_pow_HallX_nat (n : ℕ) :
    (PresentedGroup.mk relators (A ^ n * HallX) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallX * A ^ n * HallY ^ n) := by
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  set y := (PresentedGroup.mk relators HallY : PresentedGroup relators)
  have hYA : Commute y a := mk_HallY_A_comm
  have hAX : a * x = x * a * y := by
    have := mk_A_HallX
    have hl : (PresentedGroup.mk relators (A * HallX) : PresentedGroup relators) = a * x := by
      rw [map_mul]
    have hr : (PresentedGroup.mk relators (HallX * A * HallY) : PresentedGroup relators)
        = x * a * y := by rw [map_mul, map_mul]
    rw [hl, hr] at this; exact this
  suffices h : ∀ n : ℕ, a^n * x = x * a^n * y^n by
    have := h n
    show (PresentedGroup.mk relators (A ^ n * HallX) : PresentedGroup relators) =
        PresentedGroup.mk relators (HallX * A ^ n * HallY ^ n)
    have hl : (PresentedGroup.mk relators (A ^ n * HallX) : PresentedGroup relators)
        = a ^ n * x := by rw [map_mul, map_pow]
    have hr : (PresentedGroup.mk relators (HallX * A ^ n * HallY ^ n) : PresentedGroup relators)
        = x * a ^ n * y ^ n := by rw [map_mul, map_mul, map_pow, map_pow]
    rw [hl, hr]; exact this
  intro k
  induction k with
  | zero => simp
  | succ k ih =>
      calc a^(k+1) * x
          = a * (a^k * x) := by rw [pow_succ']; simp [mul_assoc]
        _ = a * (x * a^k * y^k) := by rw [ih]
        _ = (a * x) * a^k * y^k := by simp [mul_assoc]
        _ = (x * a * y) * a^k * y^k := by rw [hAX]
        _ = x * a * (y * a^k) * y^k := by simp [mul_assoc]
        _ = x * a * (a^k * y) * y^k := by rw [(hYA.pow_right k).eq]
        _ = x * (a * a^k) * (y * y^k) := by simp [mul_assoc]
        _ = x * a^(k+1) * y^(k+1) := by rw [← pow_succ', ← pow_succ']

/-- Conjugation form: `a · x · a⁻¹ = x · y` in the presented group. -/
theorem mk_A_HallX_Ainv :
    (PresentedGroup.mk relators (A * HallX * A⁻¹) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallX * HallY) := by
  set a := (PresentedGroup.mk relators A : PresentedGroup relators)
  set x := (PresentedGroup.mk relators HallX : PresentedGroup relators)
  set y := (PresentedGroup.mk relators HallY : PresentedGroup relators)
  have hYA : Commute y a := mk_HallY_A_comm
  have h1 : (PresentedGroup.mk relators (A * HallX) : PresentedGroup relators) =
      PresentedGroup.mk relators (HallX * A * HallY) := mk_A_HallX
  have hL : (PresentedGroup.mk relators (A * HallX) : PresentedGroup relators) = a * x := by
    rw [map_mul]
  have hR : (PresentedGroup.mk relators (HallX * A * HallY) : PresentedGroup relators)
      = x * a * y := by rw [map_mul, map_mul]
  have hax : a * x = x * a * y := hR ▸ hL ▸ h1
  show a * x * a⁻¹ = x * y
  rw [hax]
  -- Goal: x * a * y * a⁻¹ = x * y. hYA : Commute y a i.e. y*a = a*y, so a*y = y*a.
  have hay : a * y = y * a := hYA.symm.eq
  have : x * a * y * a⁻¹ = x * y := by
    rw [mul_assoc x a y, hay, ← mul_assoc x y a, mul_assoc (x*y) a a⁻¹, mul_inv_cancel, mul_one]
  exact this




/-- Theorem 4 of Bodart, recorded as an internal-facing axiom to be formalized.

It states that the virtually Engel group above has intermediate geodesic growth with respect to
the generating alphabet `S = {a, a⁻¹, t}`, i.e.\ `γ(n) ≍ exp(n^(3/5) log n)`. Discharging this
axiom is one of the three remaining internal steps for an unconditional positive answer to
Brönnimann's Question 3. -/
axiom theorem_4 : theorem_4_statement

/-!
## Word problem via the coordinate map

The classical word-problem witness is derived from a single sharper algebraic fact, namely
injectivity of `toCoordGroup`. Given injectivity, the coordinate model — which has decidable
equality since it is a semidirect product of two types with decidable equality — furnishes a
decision procedure for equality in the presented group.

Injectivity itself is the remaining algebraic step. It amounts to the Hall normal-form theorem
inside `PresentedGroup relators`: every element of the presented group is equal to
`PresentedGroup.mk (coordLatticeWord g)` for a unique lattice point `g` (paired with a symmetry
letter), and `coordLatticeWord_spec` above shows that distinct lattice points map to distinct
coordinates. Any single left inverse of `toCoordGroup` — for example the reconstruction map
sending a coordinate to `mk` of its Hall word — would witness injectivity, and this is precisely
what the ongoing algebraic groundwork (the Hall normal-form reconstruction, the lattice
congruence subgroup, the coordinate model of every relator) is designed to support. -/

/-!
## Image of the coordinate map lies in the lattice

The presentation generators land in `coordLattice`, and `coordLattice` is a subgroup, so the
image of every word in the presented group lies in `coordLattice`.
-/

/-- The coordinate homomorphism factored through the lattice subgroup. -/
def toCoordLattice : FreeGroup Generator →* coordLattice :=
  FreeGroup.lift coordLatticeGenerator

theorem toCoordLattice_val (w : FreeGroup Generator) :
    (toCoordLattice w).1 = FreeGroup.lift coordGenerator w := by
  refine FreeGroup.induction_on w ?_ ?_ ?_ ?_
  · simp [toCoordLattice]
  · intro g; cases g <;> simp [toCoordLattice, coordLatticeGenerator, coordGenerator]
  · intro g; cases g <;> simp [toCoordLattice, coordLatticeGenerator, coordGenerator]
  · intro x y hx hy
    simp [map_mul, hx, hy]

/-- The image of any word in the free group lies in the coordinate lattice. -/
theorem coordGenerator_lift_mem_lattice (w : FreeGroup Generator) :
    FreeGroup.lift coordGenerator w ∈ coordLattice := by
  rw [← toCoordLattice_val]
  exact (toCoordLattice w).2

/-- The image of any presented-group element lies in the coordinate lattice. -/
theorem toCoordGroup_mem_lattice (x : PresentedGroup relators) :
    toCoordGroup x ∈ coordLattice := by
  induction x with
  | H z =>
    have h := coordGenerator_lift_mem_lattice z
    simpa [toCoordGroup, PresentedGroup.toGroup] using h

/-!
## A canonical set-theoretic retract

Every element of the coordinate lattice can be reconstructed as `mk` of an explicit Hall normal
form word. The following retract lifts this reconstruction to `CoordGroup`, sending elements
outside the lattice to `1`. Injectivity of `toCoordGroup` is equivalent to `retract` being a
left inverse of `toCoordGroup`.
-/

/-- The set-theoretic retract from the coordinate model back to the presented group. On lattice
elements it is the `mk` of the Hall normal form; elsewhere it is arbitrarily set to `1`. -/
noncomputable def retract (g : CoordGroup) : PresentedGroup relators := by
  classical exact
    if h : g ∈ coordLattice then
      PresentedGroup.mk relators (coordLatticeWord ⟨g, h⟩)
    else 1

theorem retract_of_mem_lattice {g : CoordGroup} (h : g ∈ coordLattice) :
    retract g = PresentedGroup.mk relators (coordLatticeWord ⟨g, h⟩) := by
  simp [retract, dif_pos h]

/-- Injectivity of `toCoordGroup` is equivalent to `retract` being a left inverse.

Given `retract ∘ toCoordGroup = id`, `toCoordGroup` is injective. Conversely, given
injectivity, `retract ∘ toCoordGroup` and `id` agree on lattice elements after applying
`toCoordGroup`, which is enough to derive the left-inverse property from `coordLatticeWord_spec`.

This reduces the remaining internal step to a single algebraic identity in
`PresentedGroup relators`, namely that for every word `w`,
`mk (coordLatticeWord (toCoordGroup (mk w))) = mk w`. -/
theorem toCoordGroup_injective_iff_retract :
    Function.Injective toCoordGroup ↔
      Function.LeftInverse (retract : CoordGroup → PresentedGroup relators) toCoordGroup := by
  refine ⟨?_, Function.LeftInverse.injective⟩
  intro hinj x
  have hmem : toCoordGroup x ∈ coordLattice := toCoordGroup_mem_lattice x
  rw [retract_of_mem_lattice hmem]
  apply hinj
  have hspec := coordLatticeWord_spec ⟨toCoordGroup x, hmem⟩
  have hlift :
      toCoordGroup
          (PresentedGroup.mk relators
              (coordLatticeWord ⟨toCoordGroup x, hmem⟩)) =
        FreeGroup.lift coordGenerator
          (coordLatticeWord ⟨toCoordGroup x, hmem⟩) := rfl
  rw [hlift, hspec]

/-!
### Base cases of the retract identity

The retract identity `retract (toCoordGroup x) = x` is checked here on the presentation
generators. The general case reduces to a multiplication-compatibility identity for the Hall
normal form inside `PresentedGroup relators`. -/

/-- Retract sends the trivial coordinate element back to the identity of the presented group. -/
@[simp] theorem retract_one : (retract 1 : PresentedGroup relators) = 1 := by
  have hmem : (1 : CoordGroup) ∈ coordLattice := coordLattice.one_mem
  rw [retract_of_mem_lattice hmem]
  -- coordLatticeWord ⟨1, _⟩ = (1.left).hallWord * symmetryWord 1.right = 1 * 1 = 1
  show PresentedGroup.mk relators (coordLatticeWord ⟨(1 : CoordGroup), hmem⟩) = 1
  have hword : coordLatticeWord ⟨(1 : CoordGroup), hmem⟩ = 1 := by
    -- Both factors reduce to `1` in the free group.
    show EngelCoords.hallWord (1 : EngelCoords) * symmetryWord (1 : Symmetry) = 1
    simp [EngelCoords.hallWord, hallNormalWord, EngelCoords.hallM, EngelCoords.hallN, symmetryWord]
  rw [hword]
  simp

/-- Retract identity checked on the generator `a`. -/
theorem retract_toCoordGroup_of_a :
    retract (toCoordGroup (PresentedGroup.of Generator.a))
      = (PresentedGroup.of Generator.a : PresentedGroup relators) := by
  have himg : toCoordGroup (PresentedGroup.of Generator.a) = coordA := by
    unfold toCoordGroup
    rw [PresentedGroup.toGroup.of]
    rfl
  have hmem : coordA ∈ coordLattice := coordA_mem_lattice
  rw [himg, retract_of_mem_lattice hmem]
  show PresentedGroup.mk relators (coordLatticeWord ⟨coordA, hmem⟩)
        = PresentedGroup.of Generator.a
  have hword : coordLatticeWord ⟨coordA, hmem⟩ = A := by
    show EngelCoords.hallWord (engelA : EngelCoords) * symmetryWord (1 : Symmetry) = A
    simp [EngelCoords.hallWord, hallNormalWord, EngelCoords.hallM, EngelCoords.hallN,
      symmetryWord, engelA, EngelCoords.areaResidue, EngelCoords.baryResidue]
  rw [hword]
  rfl

/-- Retract identity checked on the generator `t`. -/
theorem retract_toCoordGroup_of_t :
    retract (toCoordGroup (PresentedGroup.of Generator.t))
      = (PresentedGroup.of Generator.t : PresentedGroup relators) := by
  have himg : toCoordGroup (PresentedGroup.of Generator.t) = coordT := by
    unfold toCoordGroup
    rw [PresentedGroup.toGroup.of]
    rfl
  have hmem : coordT ∈ coordLattice := coordT_mem_lattice
  rw [himg, retract_of_mem_lattice hmem]
  show PresentedGroup.mk relators (coordLatticeWord ⟨coordT, hmem⟩)
        = PresentedGroup.of Generator.t
  have hword : coordLatticeWord ⟨coordT, hmem⟩ = T := by
    show EngelCoords.hallWord (1 : EngelCoords) * symmetryWord Symmetry.flip = T
    simp [EngelCoords.hallWord, hallNormalWord, EngelCoords.hallM, EngelCoords.hallN,
      symmetryWord]
  rw [hword]
  rfl


/-- Injectivity of the coordinate representation `toCoordGroup`, equivalently the statement
that `retract` is a left inverse of `toCoordGroup`.

By `toCoordGroup_injective_iff_retract` above, this is the same as: for every word `w`,
`mk (coordLatticeWord (toCoordGroup (mk w))) = mk w` in the presented group. -/
axiom toCoordGroup_injective : Function.Injective toCoordGroup

/-- The word-problem decidability witness reconstructed from injectivity of the coordinate map.
Given two finite words in the alphabet `Generator × Bool`, equality of the represented elements
in the presented group is equivalent to equality of their images in the coordinate model, which
is decidable. -/
theorem solvableWordProblem : PresentedGroup.SolvableWordProblem relators := by
  refine ⟨fun p => ?_⟩
  by_cases h :
      toCoordGroup (PresentedGroup.evalWord relators p.1) =
        toCoordGroup (PresentedGroup.evalWord relators p.2)
  · exact isTrue (toCoordGroup_injective h)
  · exact isFalse fun hp => h (congrArg _ hp)

/-- Bodart's example has irrational geodesic growth in the sense of Question 3 of Brönnimann's
thesis. -/
axiom irrationalGeodesicGrowth :
  PresentedGroup.HasIrrationalGeodesicGrowth relators letterValue

end VirtuallyEngel
